### ISSUE TITLE
Proof of Void using interface requirement

### ISSUE THREAD

**Issue by enolan** [idris-lang/Idris-dev#3269] opened 2016-07-15 01:00 UTC
``` idris
%default total

data Point : Nat -> t -> Type where
  Nil : Point Z t
  (::) : Num t => t -> Point n t -> Point (S n) t

noNonEmptyPointInt : Not (Point (S n) Int)
noNonEmptyPointInt {n} Nil impossible

myVoid : Void
myVoid = noNonEmptyPointInt [2]
```

Typechecks on 0af1c75.

**Comment by ahmadsalim** [comment] 2016-08-03 07:56
This seems to be an issue with the coverage checker which somehow accepts `noNonEmptyPointInt` as total even though it misses the `(::)` case.

**Comment by peter-sa** [comment] 2016-08-22 16:45
I stumbled across what I believe to be this same bug recently, although I have a slightly different testcase: in this example, the function `bad` actually is total in that it matches on all possible cases, but for some reason the `impossible` declaration is accepted, even though there are argument instantiations that make that case possible.  Here is my stripped-down example:

```idris
module Inconsistency

%default total

data MyType = TyCon1 | TyCon2 | TyCon3 | TyCon4 | TyCon5

data MyTyPred : MyType -> Type where
  MyTyPredC1 : MyTyPred TyCon1
  MyTyPredC4 : MyTyPred TyCon4

bad : (t : MyType) -> Not (MyTyPred t)
bad t MyTyPredC1 impossible
bad t MyTyPredC4 impossible

witness : Void
witness = bad TyCon1 MyTyPredC1
```

This was tested on 0.12.2.

**Comment by ahmadsalim** [comment] 2016-08-22 18:56
As far as I can see this is also a coverage checker issue. It should not accept that `bad t MyTyPredC1 impossible`  since it is not. `bad TyCon1 MyTyPredC1` is a perfectly valid case (and the same with `...4`).

**Comment by peter-sa** [comment] 2016-08-22 19:09
@ahmadsalim Indeed, that's why I was thinking that this was probably the same bug; I just wanted to add the extra test case in case anything about it makes the cause of the bug more clear.  I have not worked on the Idris compiler before, but am curious about taking a look at this is a way to get started; is `checkPossible' in `Idris.Elab.Clause` the right place to start looking for the cause of this?

**Comment by ahmadsalim** [comment] 2016-08-22 19:30
@peter-sa Yeah, that is the right place!

**Comment by edwinb** [comment] 2016-12-23 12:51
I've looked at both of these, and will fix both fairly soon - they're not the same issue, but they are both problems with how impossible cases are identified.

The one in the issue itself is because 'impossible' doesn't play nicely with name disambiguation. There's a couple of better (and sound) ways of doing this which I'll try shortly.

The second one is because the checker, wrongly, doesn't think the error in the case is recoverable by unification. The offending function is `recoverableCoverage`, which has probably been written in too much of a hurry and the notion of recoverability ought to be more formal.

By the way, @ahmadsalim, I'd suggest we have a label for "Proof of Void". I would add it myself but I haven't reverse engineered the lettering system :). 

There's no way I can keep up with all the issues quickly enough, but anything labelled "Proof of Void" would be a priority to fix.

**Comment by ahmadsalim** [comment] 2016-12-23 13:19
@edwinb Sure :), I have added a `U-Inconsistency` label and assigned it to this issue.

If you are in any case interested at the labelling system, I actually did write something up in the wiki: [Issue Labelling System](https://github.com/idris-lang/Idris-dev/wiki/Issue-Labelling-System).

**Closed** 2017-03-17 15:38 UTC
Labels: C-Moderate Effort, S-Critical, U-Inconsistency, U-Surprising Behaviour, U-Totality Checking, U-Type Checking
