### ISSUE TITLE
Large number of test suite failures with new test runner

### ISSUE THREAD

**Issue by shlevy** [idris-lang/Idris-dev#2946] opened 2016-02-03 14:16 UTC
[....long log edited out...]

**Comment by jfdm** [comment] 2016-02-03 19:09
@shlevy Thanks for registering the issue. However in the interest of getting a better picture of what is going wrong, I am wondering if:

1. You can place the trace output in a gist of something so that it doesn't clog up the issue page itself. It might also resolve the UTF8 characters that are not coming through.
2. Also can you tell us more about how to reproduce the failure. For example, how you installed idris, how idris was obtained, what version you tried to install, and on what OS you used.
3. Did you make any *major* changes to your system since you last ran the test suite.

With this information we can hopefully get a clear picture of what went wrong.

**Comment by shlevy** [comment] 2016-02-04 12:43
Here's the log https://gist.github.com/shlevy/d0963c9cea235ca47b8e . I'm building with nix, using this expression:

```nix
let pkgs = import <nixpkgs> {};
  idris-expr = pkgs.runCommand "idris.nix" { src = builtins.filterSource (path: type: (builtins.baseNameOf path) != ".git") /home/shlevy/src/Idris-dev; } ''
    ${pkgs.haskellPackages.cabal2nix}/bin/cabal2nix --flag ffi --flag gmp $src | sed "s|$src|(builtins.storePath $src)|g" > $out
  '';

  overrideCabal = drv: f: drv.override (args: args // {
    mkDerivation = drv: args.mkDerivation (drv // f drv);
  });
in overrideCabal (pkgs.haskellPackages.callPackage idris-expr {}) (drv: {
  preBuild = "export LD_LIBRARY_PATH=$PWD/dist/build:$LD_LIBRARY_PATH";
})
```

Essentially, it's a standard nix cabal build, with ffi and gmp enabled, plus an extra env var for the loader to find libraries in dist/build.

with Idris at 0cbea4abaa4f876c94f3c681379f9c13e9688777 and nixpkgs at NixOS/nixpkgs@1d70e2f

**Comment by melted** [comment] 2016-02-05 13:20
There was a test suite defined in idris.cabal recently (https://github.com/idris-lang/Idris-dev/commit/2fdccaa24c587f60b5e50126bcc062ddb1591895), possibly the nix converter automatically adds running that to the end of the install and something gets snarled in the paths, like it can't find the idris executable (I assume that the tests that are succeeding are the ones that produce no output on success). Can you just try removing that from the cabal file?

**Comment by shlevy** [comment] 2016-02-05 13:23
The nix builder does `cabal test` between `cabal build` and `cabal install`, should that order be changed? I'll try removing that from the cabal file, but won't that mean the tests won't run at all?

**Comment by melted** [comment] 2016-02-05 13:41
It was more a suggestion to pinpoint the error. But the tests weren't running before (when they were only run if you did `make test_c`), so it wouldn't be a regression to turn them off.

**Comment by shlevy** [comment] 2016-02-05 13:45
Removing that fixed the issue, yeah. Should I see about moving the `cabal check` to after cabal install?

**Comment by melted** [comment] 2016-02-05 14:35
That log was driving me crazy. So I removed it :-)

**Comment by jfdm** [comment] 2016-03-11 14:42
Looking at the conversation, it is not clear if the original issues has been addressed, and that we can close this issue?

@shlevy are you happy for this to be closed, or is there a PR that needs making to ensure that yoru issues doesn't affect anyone else who installs idris using nix?

**Comment by ahmadsalim** [comment] 2016-06-06 16:42
I will close the issue since there was no response. If there is any issue that happens again, we could just reopen it or make a new one.

**Closed by ahmadsalim** 2016-06-06 16:42 UTC
Labels: I-Potentially Fixed
