### ISSUE TITLE
Unification failure for `n + n` pattern

### ISSUE THREAD

**Issue by jdevuyst** [idris-lang/Idris-dev#4212] opened 2017-11-22 02:43 UTC
Consider the following code:

```
%default total

data T : Nat -> Type where
  MkT : T (m + m) -> T m

data U : Nat -> Type where
  MkU : U m -> U (m + m)

t1 : T n -> ()
t1 (MkT _) = ()

t2 : T (n + n) -> ()
t2 (MkT _) = ()

u1 : U n -> ()
u1 (MkU _) = ()

u2 : U (n + n) -> ()
u2 (MkU _) = ()
```

`t1`, `t2`, `u1` all typecheck. `u2` fails:

```
        Type mismatch between
                U (m + m) (Type of MkU _)
        and
                U (n + n) (Expected type)
        
        Specifically:
                Type mismatch between
                        plus m m
                and
                        plus n n
```

This seems odd. Enabling `showimplicits` doesn't help clarify the matter.

It turns out that this issue can be worked around by hiding the pattern `n + n` from the compiler:

```
u2' : U (n + n) -> ()
u2' {n} foo = let (x ** prf) = lemma n
                  foo' = replace {P = U} prf foo in
              case foo' of
              (MkU _) => ()
  where lemma : (n : Nat) -> (x : Nat ** n + n = x)
        lemma n = (n + n ** Refl)
```

It's unfortunate if _hiding_ information from the compiler is a required strategy for getting programs to compile. Moreover, I don't understand why `n + n` and `m + m` can't be unified.

**Comment by ahmadsalim** [comment] 2017-11-22 08:26
They can't be unified because `+` is not an injective function.

**Comment by ahmadsalim** [comment] 2017-11-22 08:39
Note that Agda also fails with unification here, so I would say this is expected behaviour.
I think the standard way of solving this is by weakening the constraints using a sub-lemma, e.g.
`m = n + n -> U m -> ()` and then pattern matching on `U m` here.

**Comment by ahmadsalim** [comment] 2017-11-22 08:39
I will close the issue if this is alright with you.

**Closed by ahmadsalim** 2017-11-22 08:39 UTC
