### ISSUE TITLE
List value in the repl

### ISSUE THREAD

**Issue by etorreborre** [idris-lang/Idris-dev#2910] opened 2016-01-24 02:24 UTC
Sorry if I'm doing anything wrong, but I am trying to follow along the "Type-driven development with Idris" book and it looks like I can't create a list using the list syntax:
```idris
○ idris
     ____    __     _
    /  _/___/ /____(_)____
    / // __  / ___/ / ___/     Version 0.10
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/
 /___/\__,_/_/  /_/____/       Type :? for help

Idris is free software with ABSOLUTELY NO WARRANTY.
For details type :warranty.
Idris> [1, 2]
Can't disambiguate since no name has a suitable type:
        ForeignEnv.::, Prelude.List.::, Prelude.Stream.::
Idris>
```

Am I missing anything?

**Comment by etorreborre** [comment] 2016-01-24 02:27
On the other hand if I specify the type of the elements, things work fine:
```idris
○ idris
     ____    __     _
    /  _/___/ /____(_)____
    / // __  / ___/ / ___/     Version 0.10
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/
 /___/\__,_/_/  /_/____/       Type :? for help

Idris is free software with ABSOLUTELY NO WARRANTY.
For details type :warranty.
Idris> [the Int 1, the Int 2]
[1, 2] : List Int
Idris>
```

**Comment by etorreborre** [comment] 2016-01-24 02:30
More repl experimentation:
```idris
○ idris
     ____    __     _
    /  _/___/ /____(_)____
    / // __  / ___/ / ___/     Version 0.10
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/
 /___/\__,_/_/  /_/____/       Type :? for help

Idris is free software with ABSOLUTELY NO WARRANTY.
For details type :warranty.
Idris> [1, 2] ++ [3, 4]
[1, 2, 3, 4] : List Integer
Idris>
```
Works fine when appending lists. I guess that's because Idris now knows which `::` to use?

**Comment by LeifW** [comment] 2016-01-24 03:16
I'm on Idris 0.9.20.1-git:3063df6, and `[1, 2]` produces a `List Integer` at the repl for me. Maybe if it doesn't know the type of the elements it can't narrow things down between ForeignEnv and List? Stream shouldn't apply here since it's not infinite.

In general, you can fix these `Can't disambiguate` errors by using `with` to tell it which namespace to look in first. E.g. `with List [1,2]`. Can also add some more type context, e.g. `the (List _) [1,2]`.

**Comment by LiamGoodacre** [comment] 2016-01-24 16:47
Few more examples:

~~~idris
λ idris
     ____    __     _
    /  _/___/ /____(_)____
    / // __  / ___/ / ___/     Version 0.10-git:6d9ef7b
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/
 /___/\__,_/_/  /_/____/       Type :? for help

Idris is free software with ABSOLUTELY NO WARRANTY.
For details type :warranty.
Idris> [Z]
[0] : List Nat
Idris>
Idris> [0]
Can't disambiguate since no name has a suitable type:
        ForeignEnv.::, Prelude.List.::, Prelude.Stream.::
Idris>
Idris> [the Int 0]
[0] : List Int
~~~

In the second case it seems that if it can't figure out the type of `0` then it fails to find the type of `(::)`.

**Comment by xekoukou** [comment] 2016-01-24 17:02
At least, in the tutorial, there isn't a very good guide of Repl. One can
find one in the Language reference.

Most people like me will consider the language reference as a formal
document from which you cannot learn the language, and thus omit to read it.

But this language reference seems very easy to understand. So I would
suggest to move some parts of the language reference to the tutorial or
simply change the name "language reference".

**Comment by etorreborre** [comment] 2016-01-29 04:59
Thanks @LeifW for the `with` notation, I didn't know about that. I wonder though what has changed in between your version and `0.10`.  Also since the `[]` notation is language-defined syntax for lists I wonder why Idris is looking at `Stream` and `ForeignEnv`. But maybe it is language supported syntax for `::` and not specifically for lists?

**Comment by jfdm** [comment] 2016-01-29 09:10
@etorreborre 

Within Idris, the syntax: `[1,2,3,4]` is actually treated as syntactic sugar for a standard cons lists. Idris also overloads on this notation for any data type that defines the list constructors of: `Nil` and `(::)`.

Thus, during type checking when Idris sees a list: `[1,2,3,4]` it will desugar it to: `1:: 2 :: 3 :: 4 :: Nil` and then try to work out which List Type construct that overloads the `Nil` and `(::)` constructors to use. 

Recently, it was changed so that in the REPL Idris will default to `List`. In other contexts Idris will search. However, if the REPL is not defaulting to List then something might have reverted back...

**Comment by edwinb** [comment] 2016-02-14 22:29
I can't reproduce this with the current git master...

**Comment by etorreborre** [comment] 2016-02-15 11:24
@edwinb don't worry about that then, I'll just wait on the next point release, thanks.

**Comment by ahmadsalim** [comment] 2016-06-04 14:53
This seems to work as expected now, so I will close this.

**Closed by ahmadsalim** 2016-06-04 14:53 UTC
