### ISSUE TITLE
Unification error, maybe a problem in the type checker ?

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#1856] opened 2015-01-16 18:03 UTC
The following code
````
> getW : {P : a -> Type} -> Sigma a P -> a 
> getW = Prelude.Pairs.Sigma.getWitness

> cong2 : (f : a -> b -> c) -> (a1 = a2) -> (b1 = b2) -> f a1 b1 = f a2 b2
> cong2 f Refl Refl = Refl

> depCross : {P1 : alpha -> Type} ->
>            {P2 : beta -> Type} ->
>            (f : alpha -> beta ** (a : alpha) -> P1 a -> P2 (f a)) -> 
>            (a : alpha ** P1 a) -> 
>            (b : beta ** P2 b)
> depCross (f ** g) (a ** P1a) = (f a ** g a P1a)

> depCrossLemma : {P1 : alpha -> Type} ->
>                 {P2 : alpha -> Type} ->
>                 {f : (a : alpha) -> P1 a -> P2 a} ->
>                 (ac : (a : alpha ** P1 a)) -> 
>                 (getW {P = P2}) (depCross (id ** f) ac) = (getW {P = P1}) ac
> depCrossLemma (a ** c) = Refl
 
> mapGetWMapDepCrossLemma : {P1 : alpha -> Type} ->
>                           {P2 : alpha -> Type} ->
>                           {f : (a : alpha) -> P1 a -> P2 a} ->
>                           (xs : List (a : alpha ** P1 a)) -> 
>                           map (getW {P = P2}) (map (depCross (id ** f)) xs) = map (getW {P = P1}) xs
> mapGetWMapDepCrossLemma Nil = Refl
> mapGetWMapDepCrossLemma {P1} {P2} {f} (x :: xs) = ?lala where
>   gigi : (getW {P = P2}) (depCross (id ** f) x) 
>          = 
>          getW {P = P1} x
>   gigi = depCrossLemma x
>   gaga : map (getW {P = P2}) (map (depCross (id ** f)) xs)
>          =
>          map (getW {P = P1}) xs
>   gaga = mapGetWMapDepCrossLemma xs
>   s1 : map (getW {P = P2}) (map (depCross (id ** f)) (x :: xs)) 
>        = 
>        map (getW {P = P2}) ((depCross (id ** f) x) :: (map (depCross (id ** f)) xs))
>   s1 = Refl
>   s2 : map (getW {P = P2}) ((depCross (id ** f) x) :: (map (depCross (id ** f)) xs))
>        = 
>        ((getW {P = P2}) (depCross (id ** f) x)) :: (map (getW {P = P2}) (map (depCross (id ** f)) xs))
>   s2 = Refl
>   s3 : ((getW {P = P2}) (depCross (id ** f) x)) :: (map (getW {P = P2}) (map (depCross (id ** f)) xs))
>        =
>        ((getW {P = P1}) x) :: (map (getW {P = P1}) xs)
>   s3 = cong2 (::) gigi gaga
>   s4 : ((getW {P = P1}) x) :: (map (getW {P = P1}) xs)
>        =
>        map (getW {P = P1}) (x :: xs)
>   s4 = Refl
>   s5 : map (getW {P = P2}) (map (depCross (id ** f)) (x :: xs)) 
>        =
>        map (getW {P = P1}) (x :: xs)
>   s5 = trans s1 (trans s2 (trans s3 s4))
```
does not type check. The error message
````
             Can't convert
                     getWitness (depCross (MkSigma {P = \f2 => (a : alpha) -> P1 a -> P2 (f2 a)} id f) x) :: Prelude.List.List instance of Prelude.Functor.Functor, method map getWitness (Prelude.List.List instance of Prelude.Functor.Functor, method map (depCross {P1 = \a111 => P1 a111} (MkSigma {P = \f2 => (a : alpha) -> P1 a -> P2 (f2 a)} id f)) xs) = getWitness x :: Prelude.List.List instance of Prelude.Functor.Functor, method map getWitness xs
             with
                     getWitness (depCross (MkSigma {P = \f2 => (a : alpha) -> P1 a -> P2 (f2 a)} id f) x) :: Prelude.List.List instance of Prelude.Functor.Functor, method map getWitness (Prelude.List.List instance of Prelude.Functor.Functor, method map (depCross {P1 = P1} (MkSigma {P = \f2 => (a : alpha) -> P1 a -> P2 (f2 a)} id f)) xs) = getWitness x :: Prelude.List.List instance of Prelude.Functor.Functor, method map getWitness xs
```
is a bit strange. Maybe a problem in the type checker ?

**Comment by nicolabotta** [comment] 2015-01-16 18:08
I have uploaded the above example to https://github.com/nicolabotta/SeqDecProbs/blob/master/issueReport.lidr

**Comment by david-christiansen** [comment] 2015-01-18 08:24
I think that this error is not a bug, because Idris doesn't  yet have eta-rules for functions. This is similar to something we ran into at the hackathon in Gothenburg.

If you diff the two terms, the difference is the argument `P1` to `depCross`: in the first term, it is `{P1 = \a111 => P1 a111}`, and in the second term, it is `depCross {P1 = P1}`. So I think this issue is really a duplicate of #710.

**Comment by nicolabotta** [comment] 2015-01-26 09:57
David, the error appears to be related to the way Idris treats implicit argument and is, I am afraid, a bug. If you make P1 and P2 explicit, the code type checks perfectly. You can find an explicit version in https://github.com/nicolabotta/SeqDecProbs/blob/master/issueReportExpl.lidr. Best, Nicola

**Comment by david-christiansen** [comment] 2015-01-27 01:24
Making `P1` explicit will cause it to be equal to the other term, because the unification-solved one is eta-expanded, and the explicit one is not. I agree that this behavior is inconvenient, but I'm not convinced that it's a bug _per se_. It's because implicit solving finds `\x=>P1 x` while the manual version is using `P1`. These are not actually equal until #710 gets implemented.

Perhaps in the absence of #710, we should set it up to automatically eta-contract implicit arguments, or to try both eta-expanded and eta-contracted versions.

**Comment by nicolabotta** [comment] 2015-01-27 18:40
`I agree that this behavior is inconvenient, but I'm not convinced that it's a bug per se. It's because implicit solving finds \x=>P1 x while the manual version is using P1. These are not actually equal until #710 gets implemented.`

David, I do not think the problem is the lack of eta-conversions. The following example type checks:
````
> getW : {P : a -> Type} -> Sigma a P -> a 
> getW = Prelude.Pairs.Sigma.getWitness

> cong2 : (f : a -> b -> c) -> (a1 = a2) -> (b1 = b2) -> f a1 b1 = f a2 b2
> cong2 f Refl Refl = Refl

> depCross : {P1 : alpha -> Type} ->
>            {P2 : beta -> Type} ->
>            (f : alpha -> beta ** (a : alpha) -> P1 a -> P2 (f a)) -> 
>            (a : alpha ** P1 a) -> 
>            (b : beta ** P2 b)
> depCross (f ** g) (a ** P1a) = (f a ** g a P1a)

> depCrossLemma : {P1 : alpha -> Type} ->
>                 {P2 : alpha -> Type} ->
>                 {f : (a : alpha) -> P1 a -> P2 a} ->
>                 (ac : (a : alpha ** P1 a)) -> 
>                 (getW {P = P2}) (depCross (id ** f) ac) = (getW {P = P1}) ac
> depCrossLemma (a ** c) = Refl
 
> mapGetWMapDepCrossLemma : {P1 : alpha -> Type} ->
>                           {P2 : alpha -> Type} ->
>                           {f : (a : alpha) -> P1 a -> P2 a} ->
>                           (xs : List (a : alpha ** P1 a)) -> 
>                           map (getW {P = P2}) (map (depCross {P1} {P2} (id ** f)) xs) 
>                           = 
>                           map (getW {P = P1}) xs
> mapGetWMapDepCrossLemma {P1} {P2} {f} Nil = Refl
> mapGetWMapDepCrossLemma {P1} {P2} {f} (x :: xs) = s5 where
>   s1 : map (getW {P = P2}) (map (depCross (id ** f)) (x :: xs)) 
>        = 
>        map (getW {P = P2}) ((depCross (id ** f) x) :: (map (depCross (id ** f)) xs))
>   s1 = Refl
>   s2 : map (getW {P = P2}) ((depCross (id ** f) x) :: (map (depCross (id ** f)) xs))
>        = 
>        (getW {P = P2} (depCross (id ** f) x)) :: (map (getW {P = P2}) (map (depCross (id ** f)) xs))
>   s2 = Refl
>   s3 : (getW {P = P2} (depCross (id ** f) x)) :: (map (getW {P = P2}) (map (depCross (id ** f)) xs))
>        =
>        (getW {P = P1} x) :: (map (getW {P = P1}) xs)
>   s3 = cong2 (::) (depCrossLemma {f} x) (mapGetWMapDepCrossLemma {f} xs)
>   s4 : (getW {P = P1} x) :: (map (getW {P = P1}) xs)
>        =
>        map (getW {P = P1}) (x :: xs)
>   s4 = Refl
>   s5 : map (getW {P = P2}) (map (depCross (id ** f)) (x :: xs)) 
>        =
>        map (getW {P = P1}) (x :: xs)
>   s5 = trans s1 (trans s2 (trans s3 s4))
```
But replacing
````
>   s3 = cong2 (::) (depCrossLemma {f} x) (mapGetWMapDepCrossLemma {f} xs)
```
with
````
>   s3 = cong2 (::) (depCrossLemma x) (mapGetWMapDepCrossLemma xs)
```
leads to the error
````
             Can't convert
                     getWitness (depCross {P1 = \a1 => P1 a1} (MkSigma {P = \f2 => (a : alpha) -> P1 a -> P2 (f2 a)} id f) x) :: Prelude.List.List instance of Prelude.Functor.Functor, method map getWitness (Prelude.List.List instance of Prelude.Functor.Functor, method map (depCross {P1 = \a111 => P1 a111} (MkSigma {P = \f2 => (a : alpha) -> P1 a -> P2 (f2 a)} id f)) xs) = getWitness {P = \a1 => P1 a1} x :: Prelude.List.List instance of Prelude.Functor.Functor, method map {a = Sigma alpha (\a111 => P1 a111)} (getWitness {P = \a111 => P1 a111}) xs
             with
                     getWitness (depCross {P1 = P1} (MkSigma {P = \f2 => (a : alpha) -> P1 a -> P2 (f2 a)} id f) x) :: Prelude.List.List instance of Prelude.Functor.Functor, method map getWitness (Prelude.List.List instance of Prelude.Functor.Functor, method map (depCross {P1 = P1} (MkSigma {P = \f2 => (a : alpha) -> P1 a -> P2 (f2 a)} id f)) xs) = getWitness {P = P1} x :: Prelude.List.List instance of Prelude.Functor.Functor, method map {a = Sigma alpha P1} (getWitness {P = P1}) xs
```
although here P1 (and P2) are implicit in both versions. It seems to me that implicit solving sometimes finds P1 = \ x => P1 x and sometimes finds P1 = P1 (there is no manual resolution here). If this is the case, the lack of eta-conversions might just reveal a problem but would not be the problem itself. Ciao, Nicola

**Comment by nicolabotta** [comment] 2015-01-27 18:42
I have closed the issue by mistake, now it's open again.

**Comment by david-christiansen** [comment] 2015-05-17 21:59
The version with `s3` replaced now type checks in 0.9.18, so I'm closing this. Please re-open if this is a mistake!

**Closed by david-christiansen** 2015-05-17 21:59 UTC
