### ISSUE TITLE
Uppercase variable in pattern match is silently bound

### ISSUE THREAD

**Issue by vklquevs** [idris-lang/Idris-dev#4104] opened 2017-10-06 13:28 UTC
Not technically a bug, but took a while to figure out: I had a typo in a case block (in the example case, Quux) which the compiler was interpreting as a new identifier, even though it being uppercase would suggest otherwise.

If I change the data type in the example below to `data Cases = foo | bar`, I get warnings, as expected:
```
CaseError.idr:2:18:Main.foo has a name which may be implicitly bound.
This is likely to lead to problems!
```
Perhaps a similar warning could be emitted for when a case clause could unintentionally have introduced a new (uppercase) bound variable?

### Example
```
data Cases = Foo | Bar
total
main : IO ()
main = do
  putStrLn $ case Bar of
    Quux => "Matched Quux"
    _ => "Matched _"
  putStrLn $ case Just Bar of
    Just Quux => "Matched (Just Quux)"
    _ => "Matched _ (Maybe)"
```
[CaseError.idr](https://github.com/idris-lang/Idris-dev/files/1362816/CaseError.idr.txt)

### Expected Behavior
A warning signifying that `Quux` is not recognised, or similar.

### Observed Behavior
```
$ idris CaseError.idr -o testcaseerror && ./testcaseerror
CaseError.idr:7:19:warning - Unreachable case: case block in main at CaseError.idr:7:19 _ scvar
Matched Quux
Matched (Just Quux)
```

**Comment by ahmadsalim** [comment] 2017-10-07 19:55
duplicate of #2351

**Comment by ahmadsalim** [comment] 2017-10-07 19:56
Thanks for reporting the issue, but we already have it in the database.

**Closed** 2017-10-07 19:55 UTC
