### ISSUE TITLE
[1..1000] takes a long time.

### ISSUE THREAD

**Issue by zeckalpha** [idris-lang/Idris-dev#857] opened 2014-02-05 21:42 UTC
It looks like using `Nat`s in `enumFromTo` is slowing things down. Is there a way to speed this up without losing simplicity and reasonability?

**Comment by jfdm** [comment] 2015-05-22 08:23
This looks like it is related to Issue #172

**Comment by ahmadsalim** [comment] 2016-04-05 16:59
I think this is a duplicate of #172 as @jfdm mentioned, so I will close this.

**Closed by ahmadsalim** 2016-04-05 16:59 UTC
Labels: I-Duplicate
