### ISSUE TITLE
Can't use parameters from parent interface

### ISSUE THREAD

**Issue by clayrat** [idris-lang/Idris-dev#4072] opened 2017-09-14 15:03 UTC
This looks related to https://github.com/idris-lang/Idris-dev/pull/3936. However I've tried building with the latest `master` version (`1.1.1-git:f436c5f`) and it still manifests.

# Steps to Reproduce
```
import Data.Vect 

%default total
%access public export

interface Foo a where
  num : Nat

interface Foo a => Bar a where
  bar : a -> Vect num Nat

interface UnBar a where
  unbar : Vect n Nat -> a

roundtrip : (Bar a, UnBar a) => a -> a
roundtrip a = unbar {n=num} $ bar {num} a
```
# Expected Behavior
The code type checks.

# Observed Behavior
```
bug.idr:16:11:When checking right hand side of roundtrip with expected type  
        iType                                                                
                                                                             
Can't find implementation for Foo a
```

If you remove implicit passing in `roundtrip` then the error is:
```
Can't infer argument n to unbar, Can't infer argument n to bar
```

**Comment by ahmadsalim** [comment] 2017-09-30 19:13
Thanks for reporting the issue.
I think it can not infer what type `a` should be used for num, since it does not follow from unification (i.e., `num` returns `Nat` but this does not determine the `a` used in the interface).

Unless you can show this error with another example where there is such dependency I will close it as expected behaviour.

**Closed by ahmadsalim** 2017-09-30 19:13 UTC
