### ISSUE TITLE
Names do matter where they shouldn't

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#2778] opened 2015-10-30 15:50 UTC
The file

github.com/nicolabotta/SeqDecProbs/blob/master/frameworks/14-/Fraction.lidr

type checks fine. But replacing 
```
>   let gcdv1  :  (lala : Nat ** GCD lala n1 d1)
>              =  alg n1 d1 in
``` 
at lines 149-150 with
```
>   let gcdv1  :  (gcd : Nat ** GCD gcd n1 d1)
>              =  alg n1 d1 in
```
yields
```
- + Errors (1)
 `-- Fraction.lidr line 148 col 13:
     When checking right hand side of reduceLinear with expected type
             reduce alg ((n1, d1) + (n2, d2)) =
             reduce alg (reduce alg (n1, d1) + reduce alg (n2, d2))
     
     Type mismatch between
             Sigma a P (Type of (x ** pf))
     and
             Type (Expected type)
```
This seems to be a bug in 0.9.19.1-git:7b30b6d.

**Comment by nicolabotta** [comment] 2015-11-03 07:00
File moved to

https://github.com/nicolabotta/SeqDecProbs/blob/master/frameworks/14-/Fraction2778.lidr

**Comment by TimRichter** [comment] 2015-11-08 10:09
Same behaviour with cabal version idris 0.9.19.1.

**Comment by xekoukou** [comment] 2016-02-15 23:54
Is this still happening? I cannot get the error message. Isn't Sigma a P a Type?

**Comment by nicolabotta** [comment] 2016-02-16 18:34
@xekoukou: I am more or less done porting the 14- framework (and Fraction2778.lidr) to 0.10. The new version relies on a local definition of Sigma (in `Sigma.lidr` and `PairsOperations.lidr`) and does not use the `DPair` syntactic sugar. Thus, I cannot say whether the bug is still there. But what I get now when I try to type check Fraction2778.lidr are internal errors:
```
 |   When attempting to perform error reflection, the following internal error occurred:
 |           No such variable Language.Reflection.PThis is probably a bug. Please consider reporting it at https://github.com/idris-lang/Idris-dev/issues
```
I have no idea what is going on here. Best, Nicola

**Comment by david-christiansen** [comment] 2016-02-16 19:14
`P` is a constructor defined for the datatype `Language.Reflection.TT`.  For Idris (specifically, the error reflection facilty) to work right, this has to be in scope. For some reason, it isn't here.

**Comment by nicolabotta** [comment] 2016-02-17 16:14
Thanks David. The problem seems to show up whenever interface member names are used in absence of implementations. For instance

```
nicola@cirrus:~/github/SeqDecProbs/frameworks/14-$ idris +RTS -K32000000 -RTS -p contrib -p effects SimpleProb.lidr 
Type checking ./SimpleProb.lidr
*SimpleProb> :q
Bye bye
```
type checks fine. But commenting out 
```
> import NonNegRationalProperties
```
at line 10 yields
```
nicola@cirrus:~/github/SeqDecProbs/frameworks/14-$ idris +RTS -K32000000 -RTS -p contrib -p effects SimpleProb.lidr 
Type checking ./SimpleProb.lidr
When attempting to perform error reflection, the following internal error occurred:
        No such variable Language.Reflection.PThis is probably a bug. Please consider reporting it at https://github.com/idris-lang/Idris-dev/issues
*SimpleProb>
```
However, commenting out also
```
> sum ps = 1 ->
```
at line 23 makes the program type check again. Here the internal error appears to occur because we try to apply `sum` to `ps : Vect n NonNegRational` but
```
> implementation Num NonNegRational where
>   (+) = plus
>   (*) = mult
>   fromInteger = fromNat . fromIntegerNat
```
is defined in the `NonNegRationalProperties` module. Best, Nicola

**Comment by edwinb** [comment] 2016-03-25 22:25
I finally managed to reproduce the mysterious error. The problem is to do with having the wrong behaviour when hiding names. I don't know if the original error is still there, though, because too much seems to have changed.

So, I'm going to close this as "can't reproduce" - please reopen or report again if the original error emerges - and push a fix for the Language.Reflection.P error shortly.

**Closed by edwinb** 2016-03-25 22:25 UTC
