### ISSUE TITLE
Create patreon page to take donations for Idris

### ISSUE THREAD

**Issue by codygman** [idris-lang/Idris-dev#3635] opened 2017-01-28 07:17 UTC
I contribute to this [patreon project for the Rust redox OS](https://www.patreon.com/redox_os). I would likely do the same for Idris and I'm sure I'm not alone. Can someone in charge create a patreon page? Perhaps we can bolster development of Idris and allow people that wish to work full time on Idris do so.

**Comment by NobbZ** [comment] 2017-01-28 08:39
I like the idea.

But maybe, [bountysource](https://www.bountysource.com/) were a better choice? It does allow to raise funds for either a single ticket/issue, which is paid out to whomever creates the PR that fixes that issue.

But also it does have monthly payments for the projects organisation via [salt](https://salt.bountysource.com/).

**Comment by ahmadsalim** [comment] 2017-01-28 15:05
@codygman @NobbZ Thanks for the suggestions. 

I believe that this discussion is better taken on the [mailing list](https://groups.google.com/forum/#!forum/idris-lang) than here in the issue tracker. Could you kindly move the discussion there and close this issue?

**Comment by david-christiansen** [comment] 2017-01-28 15:37
I think that we can go ahead and close this directly, @ahmadsalim. It's not a bug in Idris, and having it in the database gets in the way of tracking the actual bugs.

@codygman: thanks for the suggestion, and I'm happy to hear that you'd like to support Idris development. Please write to the mailing list, where we can have a discussion about it!

**Closed by david-christiansen** 2017-01-28 15:37 UTC
Labels: F-Request For Comment
