### ISSUE TITLE
Implicits don't always work in record heads

### ISSUE THREAD

**Issue by treeowl** [idris-lang/Idris-dev#2295] opened 2015-05-18 16:21 UTC
If I have
```idris
record Cat obj (mor : (a,b : obj) -> Type) where
    constructor MkCat
    ident : (x : obj) -> mor x x
    comp' : (x,y,z:obj) -> mor y z -> mor x y -> mor x z
```
and then I try to write
```idris
record PCategory (c : Cat obj mor) where
  foo : Nat
```
I get
```
When elaborating right hand side of Cat.PCategory.free_mor:
Can't unify
        obj -> obj -> Type (Type of mor)
with
        v0 -> v1 -> Type (Expected type)

Specifically:
        Can't unify
                obj
        with
                v0
```
I tried
```idris
using (obj : Type, mor : obj -> obj -> Type)
```
but that had no effect. Using the `using` clause with

```idris
record PCategory : obj mor (Cat obj mor)
```
led to a different error, which suggested that it was ignoring the `using` in that context. I don't particularly want to have to write

```idris
record PCategory : obj (mor : obj -> obj -> Type) (Cat obj mor)
```

**Comment by ahmadsalim** [comment] 2016-05-01 08:59
I think this is a duplicate of #2266 .

**Closed by ahmadsalim** 2016-05-01 08:59 UTC
Labels: I-Duplicate
