### ISSUE TITLE
"no such variable ty" when ty isn't referenced

### ISSUE THREAD

**Issue by enolan** [idris-lang/Idris-dev#3212] opened 2016-06-09 05:25 UTC
I'm getting the message "wellfounded.idr:8:9:No such variable ty" from this file, which doesn't reference anything named ty.
```idris
data Step = LeftShort | Even

data Split : (left : List a) -> (right : List a) -> (whole : List a) -> Step -> Type where
  SplitEmpty : Split [] [] [] Even
  SplitAddLeft : x -> Split l r w LeftShort -> Split (x :: l) r (x :: w) Even
  SplitAddRight : x -> Split l r w Even -> Split l (x :: r) (x :: w) LeftShort

doSplit : (ems : List a) -> DPair (List a, List a, Step) (\(l, r, s) => Split l r w ?d)
```
Line 8 column 9 is the space after the colon on the last line. This is on fc3e88c.

**Comment by ahmadsalim** [comment] 2016-06-11 08:00
I will close this issue since I believe it is a duplicate of #2134 (and possible others), I hope this is OK.

**Closed by ahmadsalim** 2016-06-11 08:00 UTC
