### ISSUE TITLE
Can't match shadowing implicits in where clause

### ISSUE THREAD

**Issue by eraserhd** [idris-lang/Idris-dev#3911] opened 2017-07-12 22:27 UTC
```idris
data Foo = MkFoo Nat

foo : Foo -> ()
foo (MkFoo n) = ()
  where
    bar : {n : Nat} -> ()
    bar {n} = ()
```

Fails with this error:

```
When checking left hand side of Main.foo, bar:
Type mismatch between
        () (Type of Main.foo, bar n n1)
and
        _ -> _ (Is Main.foo, bar n n1 applied to too many arguments?)
```

The following things will make it work:

1. Not matching out `{n}` on the last line.
2. Renaming `n` in the where clause to `x`.

**Comment by ahmadsalim** [comment] 2017-07-19 08:40
Since most comments are on the other issue, I will close this as the duplicate of #3915 .

**Closed by ahmadsalim** 2017-07-19 08:40 UTC
