### ISSUE TITLE
Type checker accepts invalid patterns (non-existent constructors)

### ISSUE THREAD

**Issue by KesterTong** [idris-lang/Idris-dev#3189] opened 2016-05-26 02:44 UTC
The type checker will accept a pattern even when it refers to a non-existent constructor for a data type, e.g.
```
data MyData = A | B

myFunction : MyData -> String
myFunction C = ""
```
is accepted by the type checker even though C is not a constructor for MyData

**Comment by ahmadsalim** [comment] 2016-05-26 07:29
This is because `C` is treated as a pattern variable, and so it is perfectly fine. Please see #3153 for discussion on this.

I will close this as a duplicate of #3153.

**Closed by ahmadsalim** 2016-05-26 07:29 UTC
Labels: I-Duplicate

**Comment by KesterTong** [comment] 2016-05-26 15:09
Thanks for the clarification.
