### ISSUE TITLE
Elem example in tutorial doesn't typecheck

### ISSUE THREAD

**Issue by xekoukou** [idris-lang/Idris-dev#2894] opened 2016-01-14 07:50 UTC
```
import Data.Vect

testVec : Vect 4 Int
testVec = 3 :: 4 :: 5 :: 6 :: Nil

inVect : Elem 5 testVec
inVect = There (There Here)
```

**Comment by jfdm** [comment] 2016-01-14 10:17
This looks like a duplicate of #2890. The problem is related to changes to implicits. Any variable in a type signature that begins with a lower case will be treated as an implicit parameter unless otherwise quantified. 

```idris
module Main

import Data.Vect

testVec : Vect 4 Int
testVec = 3 :: 4 :: 5 :: 6 :: Nil

inVect : Elem 5 Main.testVec
inVect = There (There Here)
```

I am going to add a label to this so that someone can look at fixing the documentation.

**Comment by jfdm** [comment] 2016-03-25 22:05
Ah commit a56fad9 address this but improving the documentation. Closing this issue now.

**Closed by jfdm** 2016-03-25 22:05 UTC
Labels: Documentation
