### ISSUE TITLE
pow 2 20625 returns 0

### ISSUE THREAD

**Issue by DevJac** [idris-lang/Idris-dev#2637] opened 2015-09-19 16:00 UTC
Using Idris version 0.9.19 the following program prints `0` when run.

```
a : Integer
a = 2

b : Nat
b = 20625

main : IO ()
main = print (pow a b)
```

This happens at all optimization levels; `O1`, `O2`, and `O3`.

It's interesting to note that if `b` is decreased by 50 the program runs very fast and produces the correct answer. If `b` is increased by 50, then the program will run forever in an infinite loop and never print anything.

**Comment by DevJac** [comment] 2015-09-19 16:03
Also, if `b` is very very large the program compiled program will seg fault.

**Comment by markuspf** [comment] 2015-09-19 17:07
This is *literally* a duplicate of #2633...

**Comment by jfdm** [comment] 2015-09-19 17:07
Was this the issue that @markuspf mentioned in #2633?

**Comment by DevJac** [comment] 2016-05-02 05:08
Yes the issue @markuspf mentions in #2633 is the same as this issue. I agree this is a duplicate, and wouldn't mind this ticket being closed.

**Closed** 2016-05-02 08:34 UTC
Labels: I-Duplicate
