### ISSUE TITLE
Non-linear time to type check large pattern matches.

### ISSUE THREAD

**Issue by lodi** [idris-lang/Idris-dev#3667] opened 2017-02-22 22:07 UTC
I was working through the exercises in chapter 3 of _Type-Driven Development with Idris_, and I noticed a compile-time performance issue trying to specialize certain matrix operations.

This code takes about four seconds to type check on my machine:
```idris
slow : Vect 16 a -> Vect 16 a
slow [e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15] = ?slow_rhs
```

This code binds fewer elements, but has a nested structure.  It takes about six seconds to type check on my machine:
```idris
slower : Vect 3 (Vect 4 a) -> Vect 3 (Vect 4 a)
slower [ [e00, e01, e02, e03]
       , [e10, e11, e12, e13]
       , [e20, e21, e22, e23] ] = ?slower_rhs
```

This takes a full minute:
```idris
slowest : Vect 4 (Vect 4 a) -> Vect 4 (Vect 4 a)
slowest [ [e00, e01, e02, e03]
        , [e10, e11, e12, e13]
        , [e20, e21, e22, e23]
        , [e30, e31, e32, e33] ] = ?slowest_rhs
```

I checked if the list syntax had something to do with it, but rewriting things in `e00 :: e01 :: e02 :: e03 :: []` format didn't help.

Deconstructing the matrix on the right hand side doesn't help either:
```idris
slowest2 : Vect 4 (Vect 4 a) -> Vect 4 (Vect 4 a)
slowest2 mat =
  let [ [e00, e01, e02, e03]
      , [e10, e11, e12, e13]
      , [e20, e21, e22, e23]
      , [e30, e31, e32, e33] ] = mat in ?slowest2_rhs
```

Deconstructing the matrix in pieces takes the typechecking time back to about three seconds:
```idris
slowish : Vect 4 (Vect 4 a) -> Vect 4 (Vect 4 a)
slowish [r0, r1, r2, r3] =
  let [e00, e01, e02, e03] = r0
      [e10, e11, e12, e13] = r1
      [e20, e21, e22, e23] = r2
      [e30, e31, e32, e33] = r3 in ?slowish_rhs
```

Idris 0.99 on Windows 7 from this distribution: https://neon.se/idris/idris-0.99-win64.7z

**Comment by ahmadsalim** [comment] 2017-02-23 09:03
Thanks for the bug report. This is a duplicate of #1557 and so I will add your comment there.

**Closed by ahmadsalim** 2017-02-23 09:03 UTC

**Comment by lodi** [comment] 2017-02-23 16:27
Ok, thanks.
