### ISSUE TITLE
Not a terminator error

### ISSUE THREAD

**Issue by nicolabotta** [idris-lang/Idris-dev#3694] opened 2017-03-14 17:06 UTC
The program
```
> foo : Nat -> Nat
> foo n = m where
>   m : Nat;  m = Z
```
fails to type check with
```
- + Errors (1)
 `-- ./papers/JFP2016/Semicolon.lidr line 3 col 14:
      error: not
         a terminator, expected: ";",
         "in", end of input
         m : Nat;  m = Z 
```
Notice that
```
> foo : Nat -> Nat
> foo n = m where
>   m : Nat
>   m = Z

```
and
```
> foo : Nat -> Nat
> foo n = m where
>   m : Nat;;  m = Z
```
type check fine. I understand that fixing this issue is not particularly exciting. On the other hand, the error is very annoying, expecially when preparing Idris code for journal publication.

**Comment by ahmadsalim** [comment] 2017-03-15 09:58
Thanks for reporting the issue. I will see if I can provide a fix in the weekend.

**Comment by nicolabotta** [comment] 2017-03-15 10:05
Great, thanks Ahmad!

**Comment by ahmadsalim** [comment] 2017-03-19 08:08
@nicolabotta I have tried a few hours, but it seems that our issue is generally with the indentation parsing being unprincipled. I figured out why the issue was there, but it may be hard to fix without a proper rewrite of the parser using a more principled indentation handling.

**Comment by eraserhd** [comment] 2017-11-03 20:31
This is a duplicate of #1471

**Closed** 2017-11-04 13:03 UTC
Labels: A-Confirmed, C-Moderate Effort, S-Normal, U-Parser

**Comment by nicolabotta** [comment] 2017-11-08 09:33
@ahmadsalim Thanks!

**Comment by ahmadsalim** [comment] 2017-11-08 09:56
@nicolabotta Yeah, thanks to @eraserhd for the new parser! 👍
