### ISSUE TITLE
Segmentation fault when running a recursive program

### ISSUE THREAD

**Issue by gergoerdi** [idris-lang/Idris-dev#1515] opened 2014-09-08 14:39 UTC
Given the following module:

```idris
data Parser : Type -> Type where
     Parse : (String -> List (a, String)) -> Parser a

unParser : Parser a -> String -> List (a, String)
unParser (Parse f) s = f s

total stripPrefix : (Eq a) => List a -> List a -> Maybe (List a)
stripPrefix [] ys = Just ys
stripPrefix (x::xs) (y::ys) = if (x == y) then stripPrefix xs ys else Nothing
stripPrefix _ _  = Nothing

total token : String -> Parser ()
token tk = Parse $ \s => case stripPrefix (unpack tk) (unpack s) of
      Just s' => [((), pack s')]
      Nothing => []
      
total skip : Parser ()
skip = Parse $ \s => case unpack s of
     [] => []
     (_::s') => [((), pack s')]

instance Functor Parser where
  map f p = Parse $ \s => map (\(x, s') => (f x, s')) (unParser p s)

instance Applicative Parser where
  pure x = Parse $ \s => [(x, s)]
  pf <$> px = Parse $ \s => concat (map (\(f, s') => map (\(x, s'') => (f x, s'')) (unParser px s')) (unParser pf s))

instance Alternative Parser where
  empty = Parse $ \s => []
  p1 <|> p2 = Parse $ \s => unParser p1 s ++ unParser p2 s

total runParser : Parser a -> String -> Maybe a
runParser p s = case unParser p s of
  [(x, "")] => Just x
  _         => Nothing

between : Parser () -> Parser () -> Parser a -> Parser (List a)
between open close body = open $> loop
  where
    loop = (close $> pure []) <|> [| body :: loop |]

many : Parser a -> Parser (List a)
many p = Parse $ \s => case unParser p s of
  [] => [([], s)]
  xs => concat $ map (\(x, s') => map (\(xs, s'') => (x::xs, s'')) (unParser (many p) s')) xs

data T = A | B (List T)

instance Show T where
  show A = "A"
  show (B ts) = "[" ++ show ts ++ "]"

parse : Parser T
parse = a <|> b
  where
    a = token "A" $> pure A
    b = [| B (between (token "[") (token "]") parse) |]

parseList : Parser (List T)
parseList = many parse

test : Maybe (List T)
test = runParser parseList "A"
```

I can evaluate `test` from the REPL and get the correct result:

```idris
λΠ> test
Just [A] : Maybe (List T)
```

However, if I add a `main` function and try to compile & run it, I get a segmentation fault:

```idris
main : IO ()
main = case test of
     Nothing => return ()
     Just p => print p
```

```
$ idris  ParserTest.idr -o ParserTest
$ ./ParserTest 
Segmentation fault (core dumped)
```

**Comment by edwinb** [comment] 2016-02-14 21:56
Sorry for slowness, I didn't look at this due to the "Awaiting more information" tag - I'd expect this behaviour though. Adding 'Lazy' doesn't necessarily help because 'Lazy' only gives you one level of laziness, and it depends on when the lazy value gets forced, which here is un 'unParser'.

I'm closing this as expected behaviour (though it would still be nice not to seg fault in this circumstances)

**Closed by edwinb** 2016-02-14 21:56 UTC
Labels: Awaiting more information
