### ISSUE TITLE
Functions using `divides` do not reduce

### ISSUE THREAD

**Issue by clayrat** [idris-lang/Idris-dev#4134] opened 2017-10-19 22:07 UTC
# Steps to Reproduce
```
import Data.Primitives.Views

%default total
%access public export

half : Integer -> Integer
half n with (divides n 2)
  half ((2 * div) + mod) | DivBy prf = div

test : half 4 = 2
test = Refl
```
# Expected Behavior
Everything typechecks.
# Observed Behavior
On version `1.1.1-git:7936fbb` (commit from 19/10/17) this gives: 
```
bug.idr:11:6:When checking right hand side of test with expected type 
        half 4 = 2                                                    
                                                                      
Type mismatch between                                                 
        2 = 2 (Type of Refl)                                          
and                                                                   
        with block in Main.half 4 (divides 4 2) = 2 (Expected type)   
                                                                      
Specifically:                                                         
        Type mismatch between                                         
                2                                                     
        and                                                           
                with block in Main.half 4 (divides 4 2)               
```
Last version this worked on was that I checked was `1.1.1-git-f436c5f` (commit from 13/09/17).

**Comment by ahmadsalim** [comment] 2017-10-20 09:16
@clayrat This is because `divides` is marked as `export`, so this is expected behaviour.

You are welcome to change it to `public export` if you prefer.

**Closed by ahmadsalim** 2017-10-20 09:16 UTC
