### ISSUE TITLE
Terms in data declarations not normalized when checking if constructors' types end in the declared type.

### ISSUE THREAD

**Issue by Nolrai** [idris-lang/Idris-dev#1815] opened 2015-01-01 17:13 UTC
The following produces the error: "Example.idr:12:7:When elaborating constructor Example.mkT:
Example.myFunc is not Example.T"

Even though myFunc always evaluates to a type ending in T.

```idris
   module Example

-- This Example is silly, but the basic idea of being able to use a function and flags to build
-- constructor types can organize a very complicated set of constructors into something manageable.
-- There might be a better way to do that though. I am going to investigate what 
-- "http://aaronlevin.ca/post/106721413033/type-families-make-life-and-free-monads-simpler" is 
-- doing as it seems to be looking at the same problem.
myFunc : Bool -> Type -> Type
myFunc True t = t
myFunc False t = t -> t

data T : Type where
  mkT : (b : Bool) -> myFunc b T
```
I ran into this trying to get the following to work:
```idris

module Rev

-- I am trying to set up an description of the "reversible computations" described in 
-- 'The Two Dualities of Computation: Negative and Fractional Types"

data RevType : Type where
  one : RevType
  zero : RevType
  (+) : RevType -> RevType -> RevType
  (*) : RevType -> RevType -> RevType
  neg : RevType -> RevType
  inv : RevType -> RevType

data MonPrim : Type where
  on : MonPrim
  unit : MonPrim
  asoc : MonPrim
  comm : MonPrim

mkType : Type -> Type
mkType o = (o -> o -> Type) -> o -> o -> o -> o -> Type

toType__ : MonPrim -> o -> (o -> o -> o) -> mkType o
toType__ on   _ p f a b c d = f a b -> f c d -> f (p a c) (p b d)
toType__ unit u p f a _ _ _ = f a (p a u)
toType__ asoc _ p f a b c _ = f (p a (p b c)) (p (p a b) c)
toType__ comm _ p f a b _ _ = f (p a b) (p b a)

data RevPrim : Type where
  mkRevPrim : Bool -> Bool -> MonPrim -> RevPrim

data Rev' : Type where
  id : Rev'
  revPrim : RevPrim -> Rev'

toType_ : RevPrim -> mkType RevType
toType_ (mkRevPrim spun isAdd mp) f = 
  toType__ mp 
    (if isAdd then zero   else one) 
    (if isAdd then (Rev.(+))    else (Rev.(*))) 
    (if spun  then flip f else f  )

toType : Rev' -> mkType RevType 
toType id f a b c d = f a a
toType (revPrim x) f a b c d = toType_ x f a b c d

data Rev : RevType -> RevType -> Type where
  mkRev : 
    (a : RevType) -> 
    (b : RevType) -> 
    (c : RevType) -> 
    (d : RevType) -> 
    (r : Rev') -> 
    toType r Rev a b c d
```

**Comment by edwinb** [comment] 2015-01-09 12:47
I've just looked at this - actually it is normalising but myFunc is stuck because the 'b' in the type is a variable rather than a concrete constructor. Even though every possible path ends in a T, the elaborator doesn't explore each one (I expect an analysis of this form would be decidable, but could be really slow...).

As it is, I don't think you can get this to work exactly as you want it, I'm afraid...

**Comment by Nolrai** [comment] 2015-01-09 17:15
Thanks for looking into it! It turned out I was overthinking it a bit
anyway.

**Comment by Melvar** [comment] 2015-11-16 13:56
I think this should be closed as expected behavior; normalization works, it is just that paths are not explored.

**Closed** 2015-11-16 18:23 UTC
