### ISSUE TITLE
Syntax for handling alternative cases of matching-lets in do-blocks

### ISSUE THREAD

**Issue by be5invis** [idris-lang/Idris-dev#3765] opened 2017-04-16 18:40 UTC
Similarly to matching bindings, for example:

```idris
printfirst : Show a => List a -> IO ()
printfirst list = do
    let Just h = head' list 
           | _ => printLn "wrong"
    printLn h
```

**Comment by ahmadsalim** [comment] 2017-04-17 09:21
You are welcome to contribute this feature if interested.

**Comment by ahmadsalim** [comment] 2017-07-18 12:45
Duplicate of #3158 .

**Closed by ahmadsalim** 2017-07-18 12:45 UTC
Labels: C-Low Hanging Fruit, I-Duplicate, U-Elaboration, U-Parser, Z-Feature Request
