### ISSUE TITLE
Typechecker takes too much time and memory with a function of multiple pattern matches.

### ISSUE THREAD

**Issue by xekoukou** [idris-lang/Idris-dev#3498] opened 2016-10-19 21:15 UTC
This code takes 5 minutes to typecheck and 1Gig of memory with irdis 0.12.3-git:8e43d11. 

One function has many pattern matches which might be the cause of it.

Probably a duplicate of this issue : #2657 

```
module Test


import Data.Vect
%default total 


genT : Vect n Type -> Type
genT [] = Type
genT (x :: xs) = x -> genT xs



data FunLang: Type where
  Atom : {dt : Vect n Type} -> genT dt -> FunLang 
  And  : FunLang -> FunLang -> FunLang
  Uor  : FunLang -> FunLang -> FunLang
  Xor  : FunLang -> FunLang -> FunLang  -- d decides on that



data IndexFL : FunLang -> FunLang -> Type where
  LHere     : IndexFL fl fl
  LLeftAnd  : IndexFL x rfl -> IndexFL (And x y) rfl
  LRightAnd : IndexFL y rfl -> IndexFL (And x y) rfl
  LLeftUor  : IndexFL x rfl -> IndexFL (Uor x y) rfl
  LRightUor : IndexFL y rfl -> IndexFL (Uor x y) rfl
  LLeftXor  : IndexFL x rfl -> IndexFL (Xor x y) rfl
  LRightXor : IndexFL y rfl -> IndexFL (Xor x y) rfl


data SetFL : FunLang -> Type where
  SEmpty      : SetFL fl
  SElem      : SetFL fl
  SLeftAnd   : SetFL x -> SetFL (And x y) 
  SRightAnd  : SetFL y -> SetFL (And x y) 
  SBothAnd   : SetFL x -> SetFL y -> SetFL (And x y) 
  SLeftUor   : SetFL x -> SetFL (Uor x y) 
  SRightUor : SetFL y -> SetFL (Uor x y) 
  SBothUor   : SetFL x -> SetFL y -> SetFL (Uor x y) 
  SLeftXor   : SetFL x -> SetFL (Xor x y) 
  SRightXor  : SetFL y -> SetFL (Xor x y) 
  SBothXor   : SetFL x -> SetFL y -> SetFL (Xor x y) 




addIndexFLEmpty : IndexFL fl _ -> SetFL fl
addIndexFLEmpty LHere = SElem
addIndexFLEmpty (LLeftAnd z) = SLeftAnd $ addIndexFLEmpty z
addIndexFLEmpty (LRightAnd z) = SRightAnd $ addIndexFLEmpty z
addIndexFLEmpty (LLeftUor z) = SLeftUor $ addIndexFLEmpty z
addIndexFLEmpty (LRightUor z) = SRightUor $ addIndexFLEmpty z
addIndexFLEmpty (LLeftXor z) = SLeftXor $ addIndexFLEmpty z
addIndexFLEmpty (LRightXor z) =  SRightXor $ addIndexFLEmpty z

addIndexFL : SetFL fl -> IndexFL fl _ -> SetFL fl
addIndexFL SEmpty y = addIndexFLEmpty y
addIndexFL SElem y = SElem
addIndexFL x LHere = SElem
addIndexFL (SLeftAnd x) (LLeftAnd w) = SLeftAnd $ addIndexFL x w
addIndexFL (SLeftAnd SElem) (LRightAnd LHere) = SElem
addIndexFL (SLeftAnd x) (LRightAnd w) = SBothAnd x (addIndexFLEmpty w)
addIndexFL (SRightAnd SElem) (LLeftAnd LHere) = SElem
addIndexFL (SRightAnd x) (LLeftAnd w) = SBothAnd (addIndexFLEmpty w) x
addIndexFL (SRightAnd x) (LRightAnd w) = SRightAnd $ addIndexFL x w
addIndexFL (SBothAnd x SElem) (LLeftAnd LHere) = SElem
addIndexFL (SBothAnd SElem y) (LRightAnd LHere) = SElem
addIndexFL (SBothAnd x y) (LLeftAnd w) = SBothAnd (addIndexFL x w) y
addIndexFL (SBothAnd x y) (LRightAnd w) = SBothAnd x (addIndexFL y w)
addIndexFL (SLeftUor x) (LLeftUor w) = SLeftUor $ addIndexFL x w
addIndexFL (SLeftUor SElem) (LRightUor LHere) = SElem
addIndexFL (SLeftUor x) (LRightUor w) = SBothUor x (addIndexFLEmpty w)
addIndexFL (SRightUor SElem) (LLeftUor LHere) = SElem
addIndexFL (SRightUor x) (LLeftUor w) = SBothUor (addIndexFLEmpty w) x
addIndexFL (SRightUor x) (LRightUor w) = SRightUor $ addIndexFL x w
addIndexFL (SBothUor x SElem) (LLeftUor LHere) = SElem
addIndexFL (SBothUor SElem y) (LRightUor LHere) = SElem
addIndexFL (SBothUor x y) (LLeftUor w) = SBothUor (addIndexFL x w) y
addIndexFL (SBothUor x y) (LRightUor w) = SBothUor x (addIndexFL y w)
addIndexFL (SLeftXor x) (LLeftXor w) = SLeftXor $ addIndexFL x w
addIndexFL (SLeftXor SElem) (LRightXor LHere) = SElem
addIndexFL (SLeftXor x) (LRightXor w) = SBothXor x (addIndexFLEmpty w)
addIndexFL (SRightXor SElem) (LLeftXor LHere) = SElem
addIndexFL (SRightXor x) (LLeftXor w) = SBothXor (addIndexFLEmpty w) x
addIndexFL (SRightXor x) (LRightXor w) = SRightXor $ addIndexFL x w
addIndexFL (SBothXor x SElem) (LLeftXor LHere) = SElem
addIndexFL (SBothXor SElem y) (LRightXor LHere) = SElem
addIndexFL (SBothXor x y) (LLeftXor w) = SBothXor (addIndexFL x w) y
addIndexFL (SBothXor x y) (LRightXor w) = SBothXor x (addIndexFL y w)

```

**Comment by edwinb** [comment] 2016-11-06 16:26
It's most likely to be coverage checking that causes the problem here. Try with --nocoverage to confirm that this is the case. I don't know when I will get around to speeding up the coverage checker - it probably needs to be implemented differently.

**Comment by xekoukou** [comment] 2016-11-06 23:39
Yes without the coverage checking it takes 5 seconds instead of 5 minutes. 

I have since then changed my code and cleaned this function to 21 pattern matches and it does not increase typecheck times a lot.

**Comment by edwinb** [comment] 2016-11-19 19:24
Profiling reveals that this is caused by a 'nub' which achieves almost nothing, but still takes a long time to run.

On my machine, fixing that gets checking time down to about 25 seconds (which is about 1/5th what it took before). This is still slow, but a lot better.

There are >16000 candidate clauses for addIndexFL beyond the ones written, all of which fail to type check. So the time taken is the time to check these. Perhaps there's a better algorithm, though the ones I've read about more or less all boil down to the same thing... I'll leave this open anyway, as it's a useful example of where coverage checking can go bad.

**Comment by edwinb** [comment] 2016-11-19 21:29
Down to 10 seconds or so now... there's probably more we can do, but this kind of problem with a lot of cases to reject is always likely to take a noticeable amount of time to solve. I'll see if I can get it down a bit further, but I think it is at least usable now.

**Comment by ahmadsalim** [comment] 2016-11-20 18:03
I think 10 seconds is acceptable.

@xekoukou What do you think? can we close the issue?

**Comment by xekoukou** [comment] 2016-11-20 18:33
It is up to @edwinb if he wants to close it or not.

**Comment by ahmadsalim** [comment] 2016-11-20 18:46
I closed the issue, you or @edwinb are of course welcome to reopen it if you feel the need.

**Closed** 2016-11-20 18:46 UTC
Labels: C-Low Hanging Fruit, I-Potentially Fixed, U-Termination Checking, Z-Optimisation
