### ISSUE TITLE
typeclass duplication during proofs

### ISSUE THREAD

**Issue by enn** [idris-lang/Idris-dev#1463] opened 2014-08-07 22:00 UTC
When trying to prove a fact about a typeclass method we have two instances of the same typeclass: (constraint : E a) -> (class : E a) ->

This seems to be a bug and it blocks me from completing a proof,  here is a test case that lets you reproduce this: https://gist.github.com/enn/ab9f55c6342cf1409714

**Comment by edwinb** [comment] 2016-05-07 14:52
The cause of this (duplicate constraints) is fixed in master.

**Closed by edwinb** 2016-05-07 14:52 UTC
Labels: A-Confirmed, S-Minor, U-Elaboration, U-Surprising Behaviour
