### ISSUE TITLE
Hole in default implicit, strange REPL behaviour

### ISSUE THREAD

**Issue by erisco** [idris-lang/Idris-dev#3701] opened 2017-03-18 17:19 UTC
test.idr
```
foo :
     { default (?q) eq : String = String }
  -> String
foo = "Hello Sailor!"
```

session:
```
idris test.idr
     ____    __     _
    /  _/___/ /____(_)____
    / // __  / ___/ / ___/     Version 0.99.1-git:3dc90d3
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/
 /___/\__,_/_/  /_/____/       Type :? for help

Idris is free software with ABSOLUTELY NO WARRANTY.
For details type :warranty.
*test> :t q
No such variable q
*test> foo
"Hello Sailor!" : String
Holes: q
*test> :t q
--------------------------------------
q : String = String
*test> :r
*test> :t q
No such variable q
```

**Comment by ahmadsalim** [comment] 2017-03-18 19:50
Thanks for reporting the issue. 
I think this is because of the way expressions work in `default` where they are instantiated at call-site not at declaration site. I would almost call this expected behavior.

**Comment by ahmadsalim** [comment] 2017-03-20 21:09
I will close the issue, but if you feel strongly about it, feel free to reopen.

**Closed by ahmadsalim** 2017-03-20 21:09 UTC
Labels: C-Moderate Effort, I-Expected Behaviour, S-Normal, U-Interactive
