### ISSUE TITLE
Type error with a hole even though the hole can be filled

### ISSUE THREAD

**Issue by turion** [idris-lang/Idris-dev#4258] opened 2017-12-17 20:35 UTC
Consider this "hello world" of formalised proofs:

```idris
data N : Type where
  Zero : N
  Succ : N -> N

myPlus : N -> N -> N
myPlus Zero n = n
myPlus (Succ n) m = Succ $ myPlus n m

myPlusReduces : x = (myPlus x Zero)
myPlusReduces {x = Zero} = Refl
myPlusReduces {x = (Succ x)} = replace myPlusReduces ?whatNow
```

It returns the following error message:

```
When checking right hand side of myPlusReduces with expected type
        Succ x = myPlus (Succ x) Zero

Type mismatch between
        P (myPlus x1 Zero) (Type of replace myPlusReduces (whatNow x x P))
and
        Succ x = Succ (myPlus x Zero) (Expected type)
```

But the hole can be trivially filled with `Refl`. Is this a bug? Somehow it seems like idris could just unify "more" in order to avoid the type error.

**Comment by turion** [comment] 2017-12-17 20:38
Aside: Am I right to assume that this proof could also be done with `rewrite`, if #4254 was fixed?

**Comment by ahmadsalim** [comment] 2017-12-22 12:43
@turion It can not infer the implicit `P` argument in `replace`, you can easily use `rewrite` or `cong` to get better results I believe.

Since this is expected behaviour, I will close the issue.

**Closed by ahmadsalim** 2017-12-22 12:43 UTC
