### ISSUE TITLE
Record projections escape their Private Prison

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#2623] opened 2015-09-16 21:29 UTC
Given an Idris module `ChateauDif.idr` defined as:

```idris
module ChateauDif

%access private

record Faria where
  constructor MkFaria
  a : String

abbe : String
abbe = "i'm rich and in prison"

public
dantes : String
dantes = "Mercedes!"
````

I would expect that when imported into another module, say `Marseille.idr`, only the variable `dantes` would be exported and made available in `Marseille.idr`.

However, the following version of `Marseille.idr` will not compile:

```idris
module Marseille

import ChateauDif

data Bar : String -> Type where
  MkBar : Nat -> Bar "boo"
  MkBar' : (a : String) -> Bar a

doFoo : Bar a -> String
doFoo _ = "Morcef!"
```

Idris complains that the implicit `a` in `doFoo` is actually the projection for a record of type `Faria`. Error message being.

```
Foobar2.idr:9:13:When checking type of Foobar2.doFoo:
When checking an application of Foobar2.Bar:
        Type mismatch between
                Faria -> String (Type of a)
        and
                String (Expected type)
```

It is my understanding that `Faria` cannot escape the Chateau d'If as it is marked private, thus the projection should also be kept within the context of the module of its definition. The variable `abbe` should not be accessible either, and `dantes` should be as it is marked public.

**Comment by edwinb** [comment] 2015-09-21 16:25
This is now fixed in master. I've changed the rules for implicits so that 'a' will *always* be treated as an implicit whether there is a global 'a' or not.

**Comment by jfdm** [comment] 2015-09-21 17:19
i'm going to reopen this, as the actual error has not been fixed, the error that of leakage from records in a private module.  So given the module:

```idris
module Secret

%access private

record Foobar where
  constructor MkFoo
  foo : String
  bar : String

public
notSecret : Bool
notSecret = True
```

Importing Secret.idr into a public file will hide the constructor of `Foobar` but will export the projections and the type. If one loads `Secret.idr` in the REPL the following commands can be called.

```
λΠ> :t f
f : Foobar -> String
λΠ> :t Foobar
Foobar : Type
λΠ> MkFoo "a" "b"
No such variable MkFoo
```

The expected behaviour is that none should work.

**Comment by edwinb** [comment] 2016-01-29 22:27
I would expect the private things in Secret to be accessible at the REPL, but not to be accessible by something importing Secret. This is the intended behaviour, at least, so that you can try the definitions in the module loaded at the REPL whether private or not (they often will be private after all).

I suppose record projections should not be exported unless it's a "public export", similarly to the rules for interface methods.

**Closed** 2016-01-29 23:00 UTC
