### ISSUE TITLE
Internal error when evaluating a hole

### ISSUE THREAD

**Issue by rodlogic** [idris-lang/Idris-dev#3160] opened 2016-05-12 17:54 UTC
While following the MEAP TyDD book I was expecting to see the following when evaluating a hole:
```
*hello> greeting
?greeting : String
```

However, I get this instead:
```
*Main> greeting
(input):1:1-8:INTERNAL ERROR: Can't find name greeting
This is probably a bug, or a missing error message.
Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
Holes: Main.greeting
```

**Comment by rodlogic** [comment] 2016-05-12 17:54
I am using Idris v0.11

**Comment by gpyh** [comment] 2016-05-12 18:20
For context, this is the code:

```idris
module Main

main : IO ()
main = putStrLn ?greeting
```

**Comment by ahmadsalim** [comment] 2016-05-15 11:25
Duplicate of #2605

**Closed by ahmadsalim** 2016-05-15 11:25 UTC
