### ISSUE TITLE
Indentation is not checked frequently enough in the parser

### ISSUE THREAD

**Issue by david-christiansen** [idris-lang/Idris-dev#729] opened 2013-12-12 22:18 UTC
The following is accepted:

```
f : Int -> Int
f x = z 1 + 1 where
  z : Int -> Int
  z y =
y
```

while it should be rejected.  Quote from IRC discussion on the topic:

```
23:12 < mdmkolbe> The current parser accepts the following but according to Haskell-style indentation rules, it should be rejected: http://pastebin.com/8CcnDqTb
23:13 < mdmkolbe> The cause of this problem is that the indentation of tokens are checked at only certain points in the parser.  In order to handle indentation properly, you need to check every token's indentation.
```

He is not aware of anything that should be accepted that is rejected.

**Comment by ahmadsalim** [comment] 2016-04-05 16:54
Confirmed, still an issue today.

**Comment by steshaw** [comment] 2016-07-21 06:54
Currently, the following code is still accepted:

```idris
f : Int -> Int
f x = z 1 + 1 where
  z : Int -> Int
  z y =
y
```

but the other pattern now gives either a "variable not found" or "layout rule" error:

```idris
   do foo
      baz
 `mplus` bar
```

I believe I have a fix for the first problem that involves lightly sprinkling `indentPropHolds gtProp`.

**Comment by steshaw** [comment] 2016-07-21 08:38
Please take a look at [this pull request](https://github.com/idris-lang/Idris-dev/pull/3282). It's not a nice principled solution but it seems to work for this (narrow) use case.

**Comment by eraserhd** [comment] 2017-11-03 20:43
It looks like test cases and fixes for all the cases here have been merged, so this should be closed.  We have some more cases in #3805, and #3443 covers revamping layout handling.

**Closed** 2017-11-04 13:04 UTC
Labels: A-Confirmed, C-Minor Effort, S-Normal, U-Parser
