### ISSUE TITLE
File position as a span.

### ISSUE THREAD

**Issue by jfdm** [idris-lang/Idris-dev#1594] opened 2014-10-06 13:20 UTC
The `getFC` function in `src/Idris/ParseHelpers.hs` returns the file position using the `FC` data structure. This needs to be updated so that a span defined structure is returned.

Of note the instance `TokenParsing` of `IdrisParser` declared on line 50 needs updateding.

**Comment by ahmadsalim** [comment] 2016-04-09 16:46
This has been fixed

**Comment by LeifW** [comment] 2016-04-24 00:57
This issue is mentioned multiple times in Idris/Parser/Helpers.hs; should those references be updated?

**Comment by ahmadsalim** [comment] 2016-04-24 14:39
@LeifW Yeah, if you want to. I believe @david-christiansen fixed this.

**Comment by enolan** [comment] 2016-06-03 05:18
I don't think this is fixed. `getFC` stills returns a zero length span and is called many times. Sometimes it's called twice and a new `FC` spanning the two locations is returned, but sometimes it's not.

@david-christiansen?

I'm also not sure what solution was intended to be. Something like `MonadParsing m => m a -> m (FC, a)`?

**Comment by ahmadsalim** [comment] 2016-06-03 07:40
@enolan Thnaks, I have reopened the issue.
If you are interested, could you try to help up with this? It seems that you already have a good idea on what could be improved.

**Comment by ahmadsalim** [comment] 2016-09-18 10:56
@eamsden I have unassigned you from the issue, since I haven't seen much activity on it for a while and thought that no one should be held back if they wanted to improve on it.
If you are still interested, I can reassign you however.

**Closed** 2017-11-30 11:18 UTC
Labels: C-Low Hanging Fruit, S-Cleanup, U-Parser
