### ISSUE TITLE
Is this expected behavior of the partial evaluator?

### ISSUE THREAD

**Issue by osa1** [idris-lang/Idris-dev#2234] opened 2015-05-06 03:20 UTC
I've been playing with the partial evaluator lately and I realized this:

```idris
-- This is partially evaluated just fine...
my_pow_sd : [static] Nat -> Nat -> Nat
my_pow_sd x Z     = 1
my_pow_sd x (S k) = mult x (my_pow_sd x k)

-- But this one is not evaluated partially evaluated no matter what. See f' below.
my_pow_ss : [static] Nat -> [static] Nat -> Nat
my_pow_ss x Z     = 1
my_pow_ss x (S k) = mult x (my_pow_ss x k)

-- This is also not partially evaluated at all. See f'' below.
my_pow_ds : Nat -> [static] Nat -> Nat
my_pow_ds x Z     = 1
my_pow_ds x (S k) = mult x (my_pow_ds x k)
```

Also, we need eta-expansion for partial evaluation here:
Doesn't work: `f   = my_pow_sd 10`
Works: `f x = my_pow_sd 10 x`

Examples:

OK:
```
-- *Unlambda> :printdef f
-- f : Nat -> Nat
-- f x = PE_my_pow_28a53c2b (fromInteger 20)
-- *Unlambda> :printdef PE_my_pow_28a53c2b
-- PE_my_pow_28a53c2b : Nat -> Nat
-- PE_my_pow_28a53c2b 0 = fromInteger 1
-- PE_my_pow_28a53c2b (S k) = mult (fromInteger 10)
--                                 (PE_my_pow_28a53c2b k)
--
f : Nat -> Nat
f x = my_pow_sd 10 20
```

OK:

```
-- *Unlambda> :printdef f_ss
-- f_ss : Nat -> Nat
-- f_ss x = PE_my_pow_sd_28a53c2b x
--
f_ss : Nat -> Nat
f_ss x = my_pow_sd 10 x
```

Isn't partially evaluated:

```
-- *Unlambda> :printdef f_eta
-- f_eta : Nat -> Nat
-- f_eta = my_pow_sd (fromInteger 10)
--
-- Not partially evaluated...
--
f_eta : Nat -> Nat
f_eta = my_pow_sd 10
```

Isn't partially evaluated:
```
-- *Unlambda> :printdef f'
-- f' : Nat -> Nat
-- f' x = my_pow_ss (fromInteger 10) (fromInteger 20)
f' : Nat -> Nat
f' x = my_pow_ss 10 20
```

Also isn't partially evaluated:

```
-- *Unlambda> :printdef f''
-- f'' : Nat -> Nat
-- f'' x = my_pow_ds (fromInteger 10) (fromInteger 20)
f'' : Nat -> Nat
f'' x = my_pow_ds 10 20
```

**Comment by edwinb** [comment] 2015-05-06 07:25
The problem is the 'fromInteger' which is blocking the reduction. If you
use `S (S (S ...))` instead you'll see the expected results. I've
encountered this before but never chased it up since the partial
evaluator isn't really intended for working with nats like this - I
think it should work the way you expect.

I think the underlying problem is that it's not reducing the type class
dictionary, which could of course be a bigger problem later.

**Comment by ahmadsalim** [comment] 2016-04-16 18:11
I will close this issue since the question seems to have been answered and there is no further action points.

**Closed by ahmadsalim** 2016-04-16 18:11 UTC
Labels: F-Question
