### ISSUE TITLE
Ubuntu instructions not working on 17.04

### ISSUE THREAD

**Issue by ysangkok** [idris-lang/Idris-dev#3811] opened 2017-05-10 11:36 UTC
Install Log:
https://gist.github.com/ahmadsalim/ae8e2cf95d23940e156ac288be8f91b5

**Comment by ahmadsalim** [comment] 2017-05-10 12:41
Thanks for reporting the issue!
I have put your log in a Gist to avoid scrolling for the issue comments.

Have you tried using `stack` for installation instead?

**Comment by ysangkok** [comment] 2017-05-10 13:28
Yes, I have tried stack with system ghc using `stack --system-ghc install idris`, same problem

**Comment by david-christiansen** [comment] 2017-05-10 13:41
I think this is this issue: https://github.com/commercialhaskell/stack/issues/2712

Running the newest Stack has fixed it for me. Is your Stack up to date?

**Comment by ysangkok** [comment] 2017-05-10 14:27
@david-christiansen How can it be that issue when I am using the system GHC? The title says "stack-provided ghc". I will check the Stack version when I get home again...

**Comment by ysangkok** [comment] 2017-05-10 14:29
I am using the GHC packages from here: https://launchpad.net/~hvr/+archive/ubuntu/ghc?field.series_filter=zesty

**Comment by ysangkok** [comment] 2017-05-11 08:18
My Stack version `Version 1.3.0, Git revision 99b910d3c8e183aa376cb1e6f0341d86aed6d00e (4372 commits) x86_64 hpack-0.15.0` (https://github.com/commercialhaskell/stack/commit/99b910d3c8e183aa376cb1e6f0341d86aed6d00e) from Dec 10, 2016.

**Comment by ahmadsalim** [comment] 2017-05-11 08:26
@ysangkok It seems that this is primarily an issue with `stack` on Ubuntu, than Idris, so I am unsure how much we can fix things from here.
I think one solution, would be to provide Linux binaries for Idris, if anyone is interested in contributing that.

**Comment by melted** [comment] 2017-05-11 08:55
If you are using a system ghc why are all the error messages referring 8.0.2 ghc in /opt/ghc? Surely ubuntu doesn't install stuff there.

It would be nice if other ubuntu users could chime in with their setup and how it works (or not).

**Comment by ysangkok** [comment] 2017-05-13 09:57
@melted Herbert Valerio Riedel's packages that I linked install GHC there. So it's not the official distribution. But the most popular updated one for Ubuntu, I'd say.

**Comment by jfdm** [comment] 2017-11-09 18:31
I wondering if there are any updates to this issue. Although I use Ubuntu Mate 16.04 LTS, I do not experience issues compiling idris from source or head.

**Comment by hvr** [comment] 2017-11-10 19:37
I've tried to reproduce this on Ubuntu 17.04 with the `ghc-8.0.2 8.0.2-13.1.1~17.04` package from my PPA by building `idris-1.1.1`; however, as I expected it worked just fine for me with `cabal new-build`; Since I don't use Stack myself I don't know whether it would also have worked with Stack.

**Comment by ahmadsalim** [comment] 2017-11-11 17:15
@hvr Thanks for the update. I will close the issue.
If there is someone still experiencing issues with this, they are welcome to open a new issue or comment here to reopen.

**Closed by ahmadsalim** 2017-11-11 17:15 UTC
Labels: A-Confirmed, C-Low Hanging Fruit, F-Meta, F-Question, P-Linux, S-Normal, U-Documentation
