### ISSUE TITLE
Segmentation fault anonimous function

### ISSUE THREAD

**Issue by rbarreiro** [idris-lang/Idris-dev#2844] opened 2015-12-04 19:36 UTC
The following code generates a seg fault:
 ```idris
module Main

main : IO ()
main = do
  let f = the ((String,String) -> String -> (String, Maybe String ))  (\(_,s),y => (s, Just s))
  case snd $ f ("tst","tst2") "cenas" of
    Just z => putStr z
```
Note: don't know if it helps but, it is not a c backend specific issue as i come across it working on an alternative backend.

**Comment by ziman** [comment] 2015-12-09 12:38
This is a known erasure problem caused by me. It's apparently more than high time I solved it.

I'll look at it.

**Comment by ziman** [comment] 2015-12-11 15:29
Argument numbering seems to be strange in the lifted function. Investigating further.

**Comment by ziman** [comment] 2015-12-12 12:29
The lifted function is (internally) given a wrong type signature:
```
Builtins.Pair String String -> Builtins.Pair String String -> String -> Builtins.Pair String (Prelude.Maybe.Maybe String)
```
This confuses argument numbering of erasure.

**Comment by ziman** [comment] 2015-12-12 12:35
For the record, this is the corresponding runtime-version:
```idris
Compiled Main.case block in main at segfault.idr:9:11 =
        LFun [Inline] Main.case block in main at segfault.idr:9:11 [{e0},{e1}] case {e0} of 
        | Builtins.MkPair({e4}, {e5}) => \ {lamp1} => Builtins.MkPair({e5}, Prelude.Maybe.Just({e5}))
```

**Comment by ziman** [comment] 2015-12-12 16:31
Regardless of the surprising arguments, the code above is correct as it stands.

I was trying to be too clever in a helper function in erasure analysis and got it wrong. This will be fixed in an upcoming pull request.

**Closed** 2015-12-14 10:08 UTC
