### ISSUE TITLE
Option to show nats desugared in compiler output

### ISSUE THREAD

**Issue by eklavya** [idris-lang/Idris-dev#2507] opened 2015-08-10 17:41 UTC
Doing the (Fin 2) FZ in the REPL presents:
FZ : Fin 2

this can be improved for the newcomers if it says
FZ: Fin (S (S Z))

**Comment by david-christiansen** [comment] 2015-08-10 17:45
In particular, it made the unification performed by the implicit search difficult to understand. I propose that we add an option like 

`:set desugarNats`

that controls whether the pretty-printer does the resugaring.

**Comment by ben-schulz** [comment] 2015-09-14 17:41
I apologize if this is an ignorant question, but:

Would it be desirable for such a feature to apply exclusively to terms of type Nat?  Or are there are other types for which the option might disable resugaring by the pretty-printer?

**Comment by david-christiansen** [comment] 2015-09-14 19:36
No apology necessary at all, it's a perfectly reasonable question.

Sugar for lists is already controlled by the `showimplicits` option. `if ... then ... else ...` does not have a similar option, however.  This might also be better as an IDE feature, if any other than Emacs ever support the active term commands.

**Comment by david-christiansen** [comment] 2015-09-14 19:37
(and even unreasonable questions don't demand apologies :-])

**Comment by ben-schulz** [comment] 2015-09-15 16:31
Hi David,

Thanks for your quick reply.  I checked out a fork with the intention of working on a patch, and while it was straightforward to stub a new option into the REPL, I was unsure how to switch off resugaring without making a mess of the existing code.  Knowing that a solution should specifically target terms of type 'Nat' specifically, I think, helps clarify the scope of work.

**Comment by david-christiansen** [comment] 2015-09-15 17:45
The pretty-printer has a helper function called `snat` IIRC. This does the resugaring. There's also a pretty-printer settings record that gets passed. I'd add the option to the same place as the others (like `showimplicits`), then add a field to the pretty-printer options record, and have `snat` check the field. Then, plumb the option from the Idris state to the pretty-printer options.

**Comment by ben-schulz** [comment] 2015-09-16 06:39
I may have a patch that implements this feature, but the CI build seems to fail on just one test, namely here:

```
Ran sugar003...FAILURE
7d6
< Number 7
8a8
> Number 7
```

in `TESTS=test_js` for GHC Version 7.6.3.  This case succeeds in all the other suites.

My first reaction as to close my pull request, but I'm still wondering what the etiquette is here.  Should I keep the pull request closed until I can chase down the cause of the error?  Or it is better to leave the request open and hope for a suggestion from whoever is reviewing the request?

**Comment by jfdm** [comment] 2015-09-16 07:09
@ben-schulz I think that, generally speaking, we have no *real* etiquette w.r.t. failing PRs. You are free to leave it open for people (not just reviewers) to try and hunt down the bug, and to also publicise a bug to be found. but you are of course also free to close it will you hunt the bug down yourself.

**Comment by suhr** [comment] 2015-09-16 07:35
> Should I keep the pull request closed until I can chase down the cause of the error? Or it is better to leave the request open and hope for a suggestion from whoever is reviewing the request?

People on gh usually do the second rather than the first.

**Comment by ben-schulz** [comment] 2015-09-16 14:35
Thanks for the suggestions.  Although I don't intend to just give up on the failing test, any input would be welcome, so I think I'll reopen.

**Comment by ben-schulz** [comment] 2015-09-17 20:20
The feature appears to be implemented by commit `49fae22e4bcdfac37099ed7eadd5a644d12ab9d6`.  Can anyone else confirm?

**Comment by melted** [comment] 2015-09-17 20:34
Right, it's in. It just wasn't autoclosed via the commit message.

**Closed by melted** 2015-09-17 20:34 UTC
Labels: Feature request, Low hanging fruit, Patches welcome!, Pretty-printer
