### ISSUE TITLE
Safe String to Int function.

### ISSUE THREAD

**Issue by NightRa** [idris-lang/Idris-dev#2639] opened 2015-09-20 09:23 UTC
There should definitely be a safe function for parsing Ints from Strings in the standard library.
```idris
parseInt : String -> Maybe Int
```

The existance of an unchecked Cast from String to Int in Idris is really bewildering to me, and in my opinion, it shouldn't even exist.

```idris
x : Int
x = cast "hello"
> x = 0
```

**Comment by markuspf** [comment] 2015-09-20 09:55
Cast is a convenience hack. Use a parser instead.

**Comment by NightRa** [comment] 2015-09-20 09:57
Are you saying one needs a whole parser library to read ints, say from a console, safely?
I believe it deserves its place outside a parser library too.

**Comment by NightRa** [comment] 2015-09-20 10:00
I see this as a design mistake. Why offer the wrong, illogical, hacked solution by default and not the right thing by default?

**Comment by markuspf** [comment] 2015-09-20 10:16
What, other than a parser, would a solution use?

There is no deeper design behind Cast. Cast is a convenience, and maybe a mistake.

We'd like to see a better solution, someone will have to contribute it though.

**Comment by suhr** [comment] 2015-09-20 10:43
What about generic `parse` function for strings? Something like http://doc.rust-lang.org/std/primitive.str.html#method.parse

**Comment by jfdm** [comment] 2015-09-20 10:45
I wouldn't say cast is a 'hack' it does it's job fine. It is just that people have to explicitly provide the conversion routines. What people are talking about is the provision of `Read` instances that do the parsing. Remember that `read (show a) === a`.

**Comment by suhr** [comment] 2015-09-20 10:47
It *is* a hack as long as it provides invalid casts.

**Comment by NightRa** [comment] 2015-09-20 10:53
@markuspf Not a whole parser library, just a simple recursion / loop.
I maybe could contribute something.
"Casts" should not be losing information and should be from types that have an obvious embedding in the other. 
For Isomorphisms, casts can be made both ways.

Prisms cover what we generally want here, but restrict the implementation quite a bit.
I've been thinking about section/retraction pairs to do this sort of thing, which do allow multiple strings to be parsed to the same result, in contrast to prisms.

But first of all, there needs to be a proper function 
```idris
parseInt : String -> Maybe Int
```
The ```Cast String Int``` should be deprecated, 
and implemented for the time being as ```maybe 0 id . parseInt```

**Comment by edwinb** [comment] 2015-09-20 15:45
Casts as implemented in the Cast type class may lose information, e.g. casting a Double to an Int, or an Integer to an Int, or an Int to a Nat. It's not in the library documentation that they may lose information, and it should be.

cast as we have it is merely there as a convenience. Personally I find it very convenient a lot of the time - not every aspect of every program needs to be totally verified after all. 

A safe cast class instead would nevertheless be a useful thing to contribute to the library, probably even in the prelude, and I think we'd welcome it.

**Comment by eklavya** [comment] 2015-09-30 08:53
Hi,

Would this do?
```Idris
parseInt : String -> Maybe Int                                                                                                                                                       
parseInt ""             | StrNil = Nothing                                                                                                                                           
parseInt s                       = parseIntAux (unpack s) 0 where                                                                                                                    
    parseIntAux : (List Char) -> Int -> Maybe Int                                                                                                                                    
    parseIntAux [] acc             = Just acc                                                                                                                                        
    parseIntAux (c :: cs) acc = if (c >= '0' && c <= '9') then parseIntAux cs ((acc * 10) + (ord c) - 48)                                                                            
                                                          else Nothing 
```

I am a newbie, so I thought I'd ask before creating a PR or anything.

**Comment by david-christiansen** [comment] 2015-09-30 09:00
This code relies on a parser bug - it shouldn't be accepted. If you want to match the string's structure, then you need to have a `with (strM str)` clause, which can then be refined after pipes. The pipes as you have them should not be accepted. But you do have the right general idea here!

**Comment by eklavya** [comment] 2015-09-30 10:04
How about this one?

```Idris
parseInt : String -> Maybe Int
parseInt s with (strM s)
    parseInt ""  | StrNil                    = Nothing
    parseInt (strCons x xs) | (StrCons x xs) = parseIntAux (unpack xs) (ord x - 48) where
        parseIntAux : (List Char) -> Int -> Maybe Int
        parseIntAux [] acc        = Just acc
        parseIntAux (c :: cs) acc = if (c >= '0' && c <= '9') then parseIntAux cs ((acc * 10) + (ord c) - 48)
                                                              else Nothing
```

**Comment by jmitchell** [comment] 2015-10-31 06:37
Shouldn't `parseInt` handle negative `Int`s too?

What's the expected behavior when the number being parsed exceeds the finite range of `Int`. Currently `Int` is documented as having undefined size, so it leaves a lot of questions for the caller.

- "Is it returning `Nothing` because the number was too big or small, or because there's something else wrong with the `String`? How big is too big/small anyway?", or
- "Why do I sometimes get the number I'd expect, but other times the input `String` and `show n` are wildly different?"

These problems would go away if we provided a safe `parseInteger : String -> Maybe Integer`, and let the user decide whether and how to demote to an `Int`.

**Comment by eklavya** [comment] 2015-10-31 10:06
@jmitchell it has already been merged 
https://github.com/idris-lang/Idris-dev/blob/master/libs/base/Data/String.idr

**Comment by jmitchell** [comment] 2015-10-31 16:33
Ah, thanks @eklavya. It handles arbitrary precision, negatives, and even produces a type of class `Num` and `Neg` rather than just `Int` or `Integer`!

**Comment by ahmadsalim** [comment] 2016-05-17 18:00
So it seems that this issue has been solved, and I will therefore close it.

**Closed by ahmadsalim** 2016-05-17 18:00 UTC
Labels: C-Low Hanging Fruit, Z-Feature Request
