### ISSUE TITLE
Loading/reloading a short file sometimes takes a long time

### ISSUE THREAD

**Issue by treeowl** [idris-lang/Idris-dev#2076] opened 2015-03-30 17:59 UTC
```idris
module Sequence2

import Control.Isomorphism

%default total

data Tree23 : Nat -> Type -> Type where
    Elem : a -> Tree23 0 a
    Node2 : Nat -> Lazy (Tree23 d a) -> Lazy (Tree23 d a) ->
            Tree23 (S d) a
    Node3 : Nat -> Lazy (Tree23 d a) -> Lazy (Tree23 d a) -> Lazy (Tree23 d a) ->
              Tree23 (S d) a

size23 : Tree23 d a -> Nat
size23 (Elem _) = 1
size23 (Node2 s _ _) = s
size23 (Node3 s _ _ _) = s

-- Recursively defined size, for use in proofs only. Very slow!
rSize23 : Tree23 d a -> Nat
rSize23 (Elem _) = 1
rSize23 (Node2 _ x y) = rSize23 x + rSize23 y
rSize23 (Node3 _ x y z) = rSize23 x + rSize23 y + rSize23 z

--sizesAddNode2 : (size23 x = rSize23 x) -> (size23 y = rSize23 y) -> (size23 

--instance Sized (Tree23 d a) where
--  size = size23

data Valid23 : Tree23 d a -> Type where
  ElemValid : Valid23 (Elem x)
  Node2Valid : Valid23 x -> Valid23 y -> Valid23 (Node2 (size23 x + size23 y) x y)
  Node3Valid : Valid23 x -> Valid23 y -> Valid23 z
    -> Valid23 (Node3 (size23 x + size23 y + size23 z) x y z)

valid23ToSizeEq : Valid23 t -> size23 t = rSize23 t
valid23ToSizeEq ElemValid = Refl
valid23ToSizeEq (Node2Valid z w) =
  rewrite valid23ToSizeEq z
  in rewrite valid23ToSizeEq w in Refl
valid23ToSizeEq (Node3Valid w s t) =
  rewrite valid23ToSizeEq w
  in rewrite valid23ToSizeEq s
  in rewrite valid23ToSizeEq t
  in Refl

instance Functor (Tree23 d) where
  map f (Elem x) = Elem (f x)
  map f (Node2 s x y) = Node2 s (map f x) (map f y)
  map f (Node3 s x y z) = Node3 s (map f x) (map f y) (map f z)

data Digit : Nat -> Type -> Type where
  One : Nat -> Lazy (Tree23 d a) -> Digit d a
  Two : Nat -> Lazy (Tree23 d a) -> Lazy (Tree23 d a) -> Digit d a
  Three : Nat -> Lazy (Tree23 d a) -> Lazy (Tree23 d a) ->
          Lazy (Tree23 d a) -> Digit d a
  Four : Nat -> Lazy (Tree23 d a) -> Lazy (Tree23 d a) ->
          Lazy (Tree23 d a) -> Lazy (Tree23 d a) -> Digit d a

data ValidDig : Digit d a -> Type where
  OneValid : Valid23 x -> ValidDig (One (size23 x) x)
  TwoValid : Valid23 x -> Valid23 y -> ValidDig (Two (size23 x+size23 y) x y)
  ThreeValid : Valid23 x -> Valid23 y -> Valid23 z -> ValidDig (Three (size23 x+size23 y+size23 z) x y z)
  FourValid : Valid23 x -> Valid23 y -> Valid23 z -> Valid23 w ->
              ValidDig (Four ((size23 x+size23 y)+(size23 z+size23 w)) x y z w)

sizeDig : Digit d a -> Nat
sizeDig (One s _) = s
sizeDig (Two s _ _) = s
sizeDig (Three s _ _ _) = s
sizeDig (Four s _ _ _ _) = s

rSizeDig : Digit d a -> Nat
rSizeDig (One _ x) = rSize23 x
rSizeDig (Two _ x y) = rSize23 x + rSize23 y
rSizeDig (Three _ x y z) = rSize23 x + rSize23 y + rSize23 z
rSizeDig (Four _ x y z w) = (rSize23 x + rSize23 y) + (rSize23 z + rSize23 w)

validDigToSizeEq : ValidDig dig -> sizeDig dig = rSizeDig dig
validDigToSizeEq (OneValid y) =
  rewrite valid23ToSizeEq y in Refl
validDigToSizeEq (TwoValid z w) =
  rewrite valid23ToSizeEq z
  in rewrite valid23ToSizeEq w in Refl
validDigToSizeEq (ThreeValid w s t) =
  rewrite valid23ToSizeEq w
  in rewrite valid23ToSizeEq s
  in rewrite valid23ToSizeEq t in Refl
validDigToSizeEq (FourValid s t u v) =
  rewrite valid23ToSizeEq s
  in rewrite valid23ToSizeEq t
  in rewrite valid23ToSizeEq u
  in rewrite valid23ToSizeEq v in Refl


%elim
data FingerTree : Nat -> Type -> Type where
  Empty : FingerTree d a
  Single : Tree23 d a -> FingerTree d a
  Deep : Nat -> Digit d a -> FingerTree (S d) a -> Digit d a ->
         FingerTree d a

sizeFT : FingerTree d a -> Nat
sizeFT Empty = 0
sizeFT (Single x) = size23 x
sizeFT (Deep k x y z) = k

rSizeFT : FingerTree d a -> Nat
rSizeFT Empty = 0
rSizeFT (Single x) = rSize23 x
rSizeFT (Deep _ pr m sf) = rSizeDig pr + rSizeFT m + rSizeDig sf

{-
instance Sized (FingerTree d a) where
  size = sizeFT
  -}

data ValidFT : FingerTree d a -> Type where
  ValidEmpty : ValidFT Empty
  ValidSingle : Valid23 x -> ValidFT (Single x)
  ValidDeep : ValidDig pr -> ValidFT m -> ValidDig sf ->
              ValidFT (Deep (sizeDig pr + sizeFT m + sizeDig sf) pr m sf)

validFTToSizeEq : ValidFT t -> sizeFT t = rSizeFT t
validFTToSizeEq ValidEmpty = Refl -- ?validFTToSizeEq_rhs_1
validFTToSizeEq (ValidSingle y) =
 rewrite valid23ToSizeEq y in Refl
validFTToSizeEq (ValidDeep pr m sf) =
 rewrite validDigToSizeEq pr
 in rewrite validFTToSizeEq m
 in rewrite validDigToSizeEq sf in Refl

--validDeepToBetterSize : ValidFT (Deep s pr m sf) -> sizeFT (Deep s pr m sf) = sizeDig pr + sizeFT m + sizeDig sf
--validDeepToBetterSize (ValidDeep x y z) = ?

buildValidFT : ValidDig pr -> ValidFT m -> ValidDig sf -> {s:Nat} ->
               (s = sizeDig pr + sizeFT m + sizeDig sf) ->
               ValidFT (Deep s pr m sf)
buildValidFT vpr vm vsf sprf =
  rewrite sprf
  in ValidDeep vpr vm vsf

record Seq : Type -> Type where
  MkSeq : FingerTree 0 a -> Seq a

data ValidSeq : Seq a -> Type where
  MkValidSeq : ValidFT t -> ValidSeq (MkSeq t)

-- TODO: length and all


emptySeq : Seq a
emptySeq = MkSeq Empty

emptyValid : ValidSeq emptySeq
emptyValid = MkValidSeq ValidEmpty

singleton : a -> Seq a
singleton x = MkSeq (Single (Elem x))

singletonValid : ValidSeq (singleton x)
singletonValid {x} = MkValidSeq (ValidSingle ElemValid)

valid23to23 : {t:Tree23 d a} -> Valid23 t -> Tree23 d a
valid23to23 {t} v = t

validFTtoFT : {t:FingerTree d a} -> ValidFT t -> FingerTree d a
validFTtoFT {t} v = t

validDigToDig : {dig:Digit d a} -> ValidDig dig -> Digit d a
validDigToDig {dig} v = dig

consFT : Tree23 d a -> FingerTree d a -> FingerTree d a
consFT x Empty = Single x
consFT x (Single y) = Deep (size23 x + size23 y) (One (size23 x) x) Empty (One (size23 y) y)
consFT x (Deep s (One spr y) m sf) = Deep (size23 x + s) (Two (size23 x+spr) x y) m sf
consFT x (Deep s (Two spr y z) m sf) = Deep (size23 x + s) (Three (size23 x+spr) x y z) m sf
consFT x (Deep s (Three spr y z w) m sf) = Deep (size23 x + s) (Four (size23 x +spr) x y z w) m sf
consFT x (Deep s (Four spr y z w v) m sf) =
  Deep (size23 x + s) (Two (size23 x+size23 y) x y) (Node3 (size23 z + size23 w + size23 v) z w v `consFT` m) sf

consFTSizeRight : (node : Tree23 d a) -> (tree : FingerTree d a) ->
                  sizeFT (consFT node tree) = size23 node + sizeFT tree
consFTSizeRight node Empty = rewrite plusZeroRightNeutral (size23 node) in Refl -- ?consFTSizeRight_rhs_1
consFTSizeRight node (Single x) = Refl
consFTSizeRight node (Deep k (One spr x) y z) = Refl
consFTSizeRight node (Deep k (Two spr x w) y z) = Refl
consFTSizeRight node (Deep k (Three spr x w s) y z) = Refl
consFTSizeRight node (Deep k (Four spr x w s t) y z) = Refl

consFTValid : Valid23 x -> ValidFT t -> ValidFT (consFT x t)
consFTValid x ValidEmpty = ?consFTValid_rhs_1
consFTValid x (ValidSingle z) = ?consFTValid_rhs_2
consFTValid x (ValidDeep (OneValid y) vm vsf) = ?consFTValidDeepOne
consFTValid x (ValidDeep (TwoValid y z) vm vsf) = ?consFTValidDeepTwo
consFTValid x (ValidDeep (ThreeValid y z w) vm vsf) = ?consFTValidDeepThree
consFTValid {x} xv (ValidDeep (FourValid {x=x1} yv {y} zv {z} wv {w} uv) vm {m} vsf {sf}) =
  let newPrefixValid = TwoValid xv yv
      newPrefixSizeEq = validDigToSizeEq newPrefixValid
      newNodeValid = Node3Valid zv wv uv
      newMiddleValid = consFTValid newNodeValid vm
  in rewrite plusAssociative (size23 x) (plus (plus (plus (size23 x1) (size23 y)) (plus (size23 z) (size23 w))) (sizeFT m)) (sizeDig sf)
   in rewrite sym $ plusAssociative (size23 x1) (size23 y) (plus (size23 z) (size23 w))
    in rewrite plusAssociative (size23 y) (size23 z) (size23 w)
     in rewrite sym $ plusAssociative (size23 x1) (plus (plus (size23 y) (size23 z)) (size23 w)) (sizeFT m)
      in rewrite plusAssociative (size23 x) (size23 x1) (plus (plus (plus (size23 y) (size23 z))(size23 w)) (sizeFT m))
       in ?consFTValidDeepFour


---------- Proofs ----------

Sequence2.consFTValidDeepFour = proof
  intros
  refine buildValidFT
  trivial
  trivial
  trivial
  compute
  rewrite sym $ consFTSizeRight (Node3 (plus (plus (size23 y)(size23 z)) (size23 w)) (Delay y) (Delay z) (Delay w)) m
  rewrite sym $ consFTSizeRight (Node3 (plus (plus (size23 y)(size23 z)) (size23 w)) (Delay y) (Delay z) (Delay w)) m
  trivial


```

**Comment by edwinb** [comment] 2015-03-30 20:06
At least on my machine, this typechecks significantly quicker if commenting out consFTValid and the final proof - they are certainly the slowest definitions.

There's nothing pathologically slow about it though - when I profiled the usual things come up about propagation of unification solutions, which is annoyingly hard to make much quicker since it's about traversing large proof terms.

I'll see if I can come up with some tricks, anyway - this seems to be a useful file to take as a benchmark for elaborator efficiency.

**Comment by jfdm** [comment] 2015-04-15 07:48
Given that the problem is related to the speed of the Idris internals and that this is a useful benchmark, should this file be added to the benchmarks in the benchmarks folder?

**Comment by ahmadsalim** [comment] 2016-04-14 17:36
It seems to load pretty quickly on my machine now, and since it is marked may be fixed. I will close it.

**Closed by ahmadsalim** 2016-04-14 17:36 UTC
Labels: A-Confirmed, C-Patches Welcome, I-Potentially Fixed
