### ISSUE TITLE
Pattern name not available in where clause

### ISSUE THREAD

**Issue by anishparanjpe** [idris-lang/Idris-dev#3446] opened 2016-09-21 09:14 UTC
For the following piece of code

```idris
foo : (a, b) -> (a, b)
foo p@(a, b) = bar
  where
    bar = p
```

I get the following error

```
test.idr:4:9:
When checking right hand side of Main.foo, bar with expected type
        (a, b)

No such variable p
```

It would be useful if we could access pattern names inside a where clause.

**Comment by enolan** [comment] 2016-09-21 15:17
Duplicate of #2556.

**Comment by ahmadsalim** [comment] 2016-09-21 21:36
@enolan Thanks!

**Closed** 2016-09-21 21:36 UTC
Labels: C-Low Hanging Fruit, I-Duplicate, S-Minor, U-Elaboration
