### ISSUE TITLE
Non-exhaustive patterns in function toTT

### ISSUE THREAD

**Issue by Melvar** [idris-lang/Idris-dev#2010] opened 2015-03-18 01:49 UTC
The code
```idris
module TestExecPtr

import Providers

%language TypeProviders

%dynamic "libm" -- workaround for loading libc

getVersion : IO String
getVersion = do
  file <- foreign FFI_C "popen" (String -> String -> IO Ptr) "idris --version" "r"
  output <- do_fread file
  _ <- foreign FFI_C "pclose" (Ptr -> IO Int) file
  return output

%provide (idrisVersion : String) with Provide <$> getVersion
```
yields
```
Type checking ./TestExecPtr.idr
idris: src/Idris/Core/Execute.hs:(84,1)-(114,32): Non-exhaustive patterns in function toTT
```
The missing case seems to be for `EPtr`.

**Comment by david-christiansen** [comment] 2015-03-19 19:40
The problem is that the Haskell implementation of `prim__readFile` in the executor is expecting a handle, but it's getting a pointer. This points at a limitation in the design of the executor's representation of Idris terms, or possibly in Idris's notion of foreign values. I'll give a sane error message, but leave the issue open and think about how to fix this (and #1807 which has been surprisingly tricky).

**Comment by Melvar** [comment] 2015-03-19 23:37
So, the bug is that it expects that the user will only ever read from handles created by certain predefined calls?

**Comment by david-christiansen** [comment] 2015-03-20 12:33
It's more that the C FFI doesn't distinguish between pointers and handles, but the executor has to in order to use Haskell functions to read from handles. There's a design issue to figure out that's not a quick fix.

**Comment by Melvar** [comment] 2015-03-20 13:44
Well, either the executor must know how to read from `FILE *`s, or it must convert them into handles to use its Haskell functions, or it must forbid calling arbitrary C functions that create them. Currently it is effectively doing the last in an annoyingly roundabout way (by giving up only once one tries to use them).

**Comment by david-christiansen** [comment] 2015-03-20 15:56
I certainly can't think of a less-annoying way than the present.

An alternative might be to have a separate FFI descriptor for the executor that doesn't conflate handles and pointers, and then do a bit of other C/libffi magic inside the executor. But that will have to wait a bit, I'm afraid!

**Comment by ahmadsalim** [comment] 2016-04-12 20:32
I think the discussion has stalled and the mentioned error is fixed, so I will close this one.

**Closed by ahmadsalim** 2016-04-12 20:32 UTC
