### ISSUE TITLE
Attempting to evaluate a hole results in an INTERNAL ERROR

### ISSUE THREAD

**Issue by rpglover64** [idris-lang/Idris-dev#2605] opened 2015-09-11 18:52 UTC
To reproduce:
1. Using Idris version 0.9.19, load a file with a hole (I used the "hello.idr" example from the _Type Driven Development with Idris_ prerelease)
2. Type the name of the hole at the prompt ("greeting" in this case) and press enter.
3. Observe the following

```
*hello> greeting
(input):1:1-9:INTERNAL ERROR: Can't find namegreeting
This is probably a bug, or a missing error message.
Please consider reporting at https://github.com/idris-lang/Idris-dev/issues
Holes: Main.greeting
```

**Comment by jfdm** [comment] 2015-09-11 19:02
Thanks for the error message. I can confirm it does exist and someone will have a look at it ASAP.

Also to note that another issue is related to error message formatting and that there should be a space between "Can't find name" and greeting.

**Comment by NightRa** [comment] 2015-09-19 14:39
Encountered this error too.

**Comment by ahmadsalim** [comment] 2016-05-15 11:39
Duplicate of #2467.

**Closed by ahmadsalim** 2016-05-15 11:39 UTC
Labels: A-Confirmed
