### ISSUE TITLE
Auto-implicits don't show up in :doc

### ISSUE THREAD

**Issue by arianvp** [idris-lang/Idris-dev#3264] opened 2016-07-10 21:46 UTC
Idris Version: 0.12

Given the following datatype:

```
data Api : capture -> query -> req -> resp -> Type where
  |||
  ||| @ paths  a list of paths we can choose from
  ||| @ thereShouldBePaths  A proof that we have at least one path defined
  ||| @ noOverlappingPaths  A Proof that we have no paths that overlap
  OneOf : (Eq capture, Eq query)
        => (paths : List (Path capture query req resp))
       -> {auto thereShouldBePaths: NonEmpty paths}
       -> {auto noOverlappingPaths: map Servis.extractPathInfo paths = nub (map Servis.extractPathInfo paths)}
       -> Api capture query req resp

```

Expected behaviour of `:doc`:

```
Servis.OneOf : Eq capture => Eq query => (paths : List (Path capture
                                                             query
                                                             req
                                                             resp)) ->
    Api capture query req resp
    
    Arguments:
        paths : List (Path capture query req resp)  -- a list of paths we can choose from
        
        (implicit) thereShouldBePaths : NonEmpty paths  -- A proof that we have at least one
        path defined
        
        (implicit) noOverlappingPaths : map extractPathInfo paths =
                                        nub (map extractPathInfo paths)  -- A Proof that we have no paths
        that overlap
        
    The function is Total

```

Actual behaviour:
```
Servis.OneOf : Eq capture => Eq query => (paths : List (Path capture
                                                             query
                                                             req
                                                             resp)) ->
    {auto thereShouldBePaths : NonEmpty paths} ->
    {auto noOverlappingPaths : map extractPathInfo paths =
                               nub (map extractPathInfo paths)} -> Api capture query req resp
    
    Arguments:
        paths : List (Path capture query req resp)  -- a list of paths we can choose from
        
    The function is Total

```

**Comment by jfdm** [comment] 2016-07-13 07:40
@arianvp Thanks for the issue report. IdrisDoc was a contributed feature of Idris, as part of a Student Project. It is my understanding that the scope of the project was purposefully constrained. An understandable notion.

I think that all labelled documentation should be present. I shall have a quick look today to see if I can fix it, otherwise: PRs welcome!

**Comment by jfdm** [comment] 2016-07-13 08:58
So, from a cursory glance something interesting is happening with Idris and implicits. This *may or may not* be the cause of auto implicit documentation not being displayed. 

However, for those interested in this issue, here is a small MFE:

```idris
module IdrisDocIssue

import Data.List

%default total

||| A foobar with an auto implicit
data Foobar : Type where
  ||| New Foo
  |||
  ||| @xs Some `xs`
  ||| @ys Some `ys`
  ||| @prf1 A prf
  NewFoo : (xs : List String)
        -> (ys : List Nat)
        -> {auto prf : NonEmpty ys}
        -> Foobar
```

**Comment by jfdm** [comment] 2016-07-13 09:20
There seems to be a case missing in the showing of arguments. Will try and fix if possible.

**Comment by jfdm** [comment] 2016-07-13 09:55
There is a PR #3267 that fixes IdrisDoc to print documentation for auto implicits. This issue should auto close once the PR has been merged.

**Closed** 2016-07-13 11:31 UTC
Labels: A-Confirmed, C-Moderate Effort, U-Interactive, U-Surprising Behaviour

**Comment by arianvp** [comment] 2016-07-13 12:38
Thanks a bunch!
