### ISSUE TITLE
Idris 0.11 fails to build with ghc 8.0 with an odd error

### ISSUE THREAD

**Issue by mitchty** [idris-lang/Idris-dev#3127] opened 2016-04-23 16:08 UTC
Alright, I don't necessarily think this is ghc 8.0 specific, nor am I saying support 8.0 yet. But I'm getting the same error someone did a while back.

https://groups.google.com/forum/#!msg/idris-lang/ioo0BXnr5WE/R57e7TjFtf0J

Specifically that. Now a bit of a preface, I've ported ghc to alpine linux which runs on musl libc. Specifically I found this behavior out after I managed to get ghc 8.0 building for arm on that platform. Note, 7.10.3 has issues with llvm bugs, so no joy on getting that to work. Regardless, arm isn't needed to replicate things.

To make things simpler I have docker hub docker images setup, one with my work in progress (an very much don't use this port yet) port of 8.0.

Compare, the prior 7.10.3 port builds idris fine, this docker file will demonstrate:
```
from mitchty/alpine-ghc:latest

run apk update && apk upgrade && apk add alpine-sdk ncurses-dev libffi-dev zlib-dev
run cabal update
run cabal install --global idris

cmd idris
```

That will work fine. However building via this dockerfile with 8.0 fails in the same way 7.11.$DATE did in the past in that prior thread. Regardless, this docker file shows the same issue:
```
from mitchty/alpine-ghc:8.0

run apk update && apk upgrade && apk add alpine-sdk ncurses-dev libffi-dev zlib-dev                                    
run cabal update
workdir /tmp
run cabal get idris
workdir /tmp/idris-0.11
run cabal install --allow-newer --dependencies-only
run cabal install --allow-newer || /bin/true
```

I have looked at possible sources of suspected UTF-8 weirdness, but musl libc really isn't that different from regular glibc here. If anything it treats locales more sanely in regards to utf8. Additionally, the fact that 7.10.3 works somewhat negates the libc locale situation in my opinion. pdxleif in irc suggested pursuing LANG/LC_ALL etc... but even in tests of things via regular olde c, I can't find any significant differences from gnu libc.

I'm willing to help out debug but I'm still new to idris, and while this port of haskell was partially to eventually be able to compile idris programs on alpine arm, I'm in over my head with how much I have to learn. But point me in the right direction and I'll try to figure things out, given the house of cards this whole thing is so far I'm willing to understand that it might be i've ported ghc 8.0 wrong in some way, but could use some help as to where to start looking.

But it could be a fun bug that is specific to ghc 8.0 somehow too. Hopefully i'm not a harbinger of things to come in that regard. Only I have some helpful docker files to help debug. 

Cheers!

**Comment by mitchty** [comment] 2016-04-23 16:32
Forgot to post a link to the build log file in the primary issue.

https://gist.github.com/mitchty/9d40711443939fb10d07e8947fc83dcb

**Comment by ahmadsalim** [comment] 2016-05-24 18:38
@mitchty Have you tried using trifecta 1.4 or something like that?

**Comment by mitchty** [comment] 2016-05-25 15:08
@ahmadsalim haven't had a huge amount of time to test out pinning most of the packages but I know @LeifW had pinpointed this down more to newlines not getting parsed right if I remember correctly.

I was looking to maybe try rewriting the Idris parser to use Text instead of String to see if that would help at all but work has kept me busy of late so no fun night projects.

**Comment by LeifW** [comment] 2016-05-25 16:23
I don't think it's anything whitespace related - that was just a guess. The files looked the same to me at the character by character level when I ran "readFile" on them w/ that GHC 8 build.

I'd be curious to find out if anyone else is using trifecta on ghc 8. I'd like to have a demo of parsing a haskell-like language with that setup just to check.

**Comment by david-christiansen** [comment] 2016-05-27 17:59
I wonder if this isn't an issue of a very old Idris binary from before docstring syntax being run instead of the correct one.

**Comment by LeifW** [comment] 2016-05-27 20:58
Pretty sure it's just a GHC 8 thing. Was able to reproduce with @mitchty's build of GHC 8 in a docker image. Tried again w/ GHC 8.0.1 release on MacOSX just now. Same. You can remove that docstring stuff and the parsing will just fail further down. Could provide builds w/ GHC 8 for various platforms if people want to poke at it (or chroots, docker images, etc). Neither trifecta nor parsers are "released" for GHC 8 yet.

**Comment by mitchty** [comment] 2016-05-27 23:42
@david-christiansen I doubt it, as an example I basically ported ghc to this platform, both x86 and arm, so no old idris to speak of on a newly bootstrapped platform.

**Comment by ahmadsalim** [comment] 2016-06-03 09:24
I will close this as a duplicate of #3193 in order to focus the discussion. Thanks for the report!

**Closed by ahmadsalim** 2016-06-03 09:24 UTC
