### ISSUE TITLE
Constructing lists takes a long time

### ISSUE THREAD

**Issue by TheWizardTower** [idris-lang/Idris-dev#4283] opened 2018-01-07 19:19 UTC
Hello!

While working on the idris-koans project, I encountered a strange behavior. Comparing

`[1..13] == [1..13]`

ran very quickly, and gave the expected result of `True : Bool`. However, comparing

`[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13] == [1..13]`

takes a _very_ long time to execute. (I haven't seen it finish yet)

Even evaluating the list literal takes an exceedingly long time. However, if you annotate the type:

`the (List Integer) [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]`

This finishes immediately, as does the above comparison to `[1..13]`

Please attach complete source files that exhibit the issue in addition
to quoting from them here.

# Steps to Reproduce

Evaluate `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]` in the repl, or typecheck that value in a file via `:l`

# Expected Behavior

It finishes immediately.

# Observed Behavior

It takes a very long time.

**Comment by ahmadsalim** [comment] 2018-01-17 17:53
Thanks for reporting the issue! This seems to be similar to #4290 , but since there are more discussions there I will close this one even though it was opened before.

**Comment by ahmadsalim** [comment] 2018-01-17 17:53
Duplicate of #4290

**Closed by ahmadsalim** 2018-01-17 17:53 UTC

**Comment by ziman** [comment] 2018-01-18 11:24
In #4290, we talk about the representation of `Nat`. However, already `[1,2,3,4,5,6]` is *slow* on my machine, compared to `[1..6]`, which is fast.

I suspect that something else is going on here with list literals and we should reopen this bug.

**Comment by ziman** [comment] 2018-01-18 11:26
By the way, `the (List Nat) [1,2,3,4,5,6]` runs fast.

I suspect that Idris is doing backtracking while giving types to the individual elements.
